### ISSUE TITLE
Error Loading mod on most recent version of 1.15.2 Forge

### ISSUE THREAD

**Issue by TheGoldenDragon2033** [WolfShotz/Wyrmroost#101]
![image](https://user-images.githubusercontent.com/72619539/95641999-c0f91c00-0a73-11eb-87f1-3ea8ea94ff76.png)

**Comment by WolfShotz** [comment]
Can you provide a log?

**Comment by TheGoldenDragon2033** [comment]
[2020-10-09-4.log.gz](https://github.com/WolfShotz/Wyrmroost/files/5358219/2020-10-09-4.log.gz) I think this is the one

**Comment by WolfShotz** [comment]
Please Update your forge Version.

![image](https://user-images.githubusercontent.com/32242079/95642279-8d1ef600-0a75-11eb-8b21-a7c6ce86e9be.png)
