### ISSUE TITLE
Flying Dragons cannot fly leashed

### ISSUE THREAD

**Issue by GundunUkan** [WolfShotz/Wyrmroost#105]
Remember how RRs died of belly flops? Well, it's the same for alpines.

**Comment by WolfShotz** [comment]
Explain this better. Dragons that are physically unable to fly (with exceptions) are meant to take fall damage

**Comment by GundunUkan** [comment]
Alpines (obviously) are able to fly. If you leash one it automatically goes into landed mode, and when it reaches the ground it takes fall damage, similar to how RRs used to take fall damage if they were knocked unconscious in the air.

**Comment by WolfShotz** [comment]
rebase: "Dragons cannot fly leashed"
