### ISSUE TITLE
Butterfly leviathan server crash

### ISSUE THREAD

**Issue by CrypticSiri** [WolfShotz/Wyrmroost#106]
**Logs:**
Crash log 1: https://hastebin.com/gaqicacidu.yaml
Crash log 2: https://pastebin.com/PcQ46ajL
Full server log: https://pastebin.com/5StMifCL

**Steps to Reproduce:**
1. In survival, approach a butterfly leviathan and wait for it to strike a player with lightning.

**Description of issue:**
I'm running a 1.15.2-forge-31.2.44 server with Wyrmroost 1.2.2, and whenever a butterfly leviathan attempts to attack a player with lightning, the server crashes. Two crash logs are created whenever this occurs, so I included both of them. This error did not occur with previous versions of Wyrmroost.

**Comment by WolfShotz** [comment]
Fixed in 1.2.3
