### ISSUE TITLE
Spawn Rates go Down and Despawning Becomes a Thing

### ISSUE THREAD

**Issue by CommandBlockGuru** [WolfShotz/Wyrmroost#108]
**Logs:** {Link(s) to GitHub Gist, Pastebin, etc with full latest.log and/or crash report}

**Steps to Reproduce:**
 1. Just wait
 2. Wait sum more
 3. Oh look my house is being invaded by literally millions of overworld drakes, slowly killing my framerate. How lovely.

**Description of issue:**
Put the spawn rates down and allow creatures to despawn. I feel like drags should be a lot more rare. I mean there's that and the fact that as soon as I spawn, I'm tackled by an overworld drake and die 20+ times till I just delete the mod. And if I do stay, it doesn't even despawn. Anyways, I don't want someone to tell me about editing the config file because there's been A LOT of complaining about this on the wiki, and I'm guessing the Discord as well, even leading players to delete the mod cause they're sick of it. My recommendation is to maybe make spawning similar to the Ice and Fire mod's creature spawning (Not like the roosts though they're way too close together). Anyways, I hope that you at least think about what I said and don't say "JuSt EdIt iT fRoM tHe CoNfIg FiLe" "Closed discussion". I want it down in general, not just having to edit it in the config since peeps may not know how to or are confused by it. Anyways, thank you for coming to my rant. Goodbye.

**Comment by WolfShotz** [comment]
First of all, your the only person ive seen complain about this lol.
Second of all, that makes 0 sense. Overworld Drakes only spawn on chunk generation. They do not spawn over time. So you either have a mod changing the spawn rates, or something else is very wrong.

**Comment by WolfShotz** [comment]
The spawn rates have been re-evaluated (and some completely re-done), hopefully this was what you were looking for.
