### ISSUE TITLE
Royals ( or presumably other dragons too? ) in unloaded chunks in the nether disappear

### ISSUE THREAD

**Issue by VakyPanda** [WolfShotz/Wyrmroost#109]
**Steps to Reproduce:**
 1. Spawn Royal red
 2. Tame it
 3a. Take it into nether ( via soul crystal ) [ continued at step 4 ]
 3b. Take it into nether ( via portal ), it disappears
 4. Start flying and leave the server
 5. Upon coming back, the royal is missing

**Description of issue:**
Royal Reds ( not tested with other dragons, most likely the same for them too ), disappear on servers when they either go into a portal, or the player leaves the server. This happened to me while flying through the nether and the server kicked me, upon joining back i found the royal missing and I fell from the height I was flying with it. A friend on the same server experienced a similar issue, with the royal going through the portal, but when we arrived on the other side, it wasn't there.

Wyrmroost version : 1.2.1
Game version : 1.15.2
Experienced on servers, has not been tested on singleplayer

**Comment by WolfShotz** [comment]
Fuck portals

**Comment by WolfShotz** [comment]
Can't seem to recreate, but I will keep this open in case others have more to comment.

**Comment by WolfShotz** [comment]
There's been no other reports of this in a month, so rip
