### ISSUE TITLE
Slowfall Breaks Sliver Gliders

### ISSUE THREAD

**Issue by Jceratops** [WolfShotz/Wyrmroost#11]
When I was messing around I gave a tamed Sliver glider slow fall, when I took it off sit, it started to levitate off the ground.

**Comment by WolfShotz** [comment]
Because it has.. slow fall.. lol. Slowfall screws with the way in which the current flight works. This should be resolved in wyrmroost 1.1 (Where I rework the flight mechanics etc.)

**Comment by Jceratops** [comment]
Ok
I just wanted to bring it to the dev's attention. It confused me as it was slow fall, and not levitation
