### ISSUE TITLE
Crash apon hovering over someone else's dragon crystal in multiplayer

### ISSUE THREAD

**Issue by Dragonmatic** [WolfShotz/Wyrmroost#113]
[latest.log](https://github.com/WolfShotz/Wyrmroost/files/5372306/latest.log)

**Comment by WolfShotz** [comment]
Line 129 of SoulCrystal, getting the owner for the description of the item.

getOwner() is NULLABLE! This player can either be offline OR NOT NEAR!
Owner needs a null check
