### ISSUE TITLE
Male overworld drake commited glutton and not wanting to breed

### ISSUE THREAD

**Issue by Raptorlos** [WolfShotz/Wyrmroost#114]
in 1.2.4. m version 1.15.2
 1. tame a OWD
 2. a skeleton hits male
 3. walks away so it teleports to me 
 4. get it back in the cage and heal him with wheat
 5. try breeding them 
 6. male not wanting to enter smexy mode

so yea once hit by a skeleton arrow, it killing the skeleton and teleporting (altough i doubt thats part of the issue but ill say it anyway)
the male maybe both but only male got hit dont want to breed and want to comit fatto = i can spam feed the owd wheat for infinity.

**Comment by WolfShotz** [comment]
Did u try... waiting? Animals (including our dragons) have a breed cooldown

**Comment by Raptorlos** [comment]
i didnt breed them for multipliys days and as said if it was cooldown why was the male accepting wheat? the female had hearts but not the male

**Comment by WolfShotz** [comment]
How many times has this particular drake bred?

**Comment by Raptorlos** [comment]
twice and i only have 1 pair

**Comment by WolfShotz** [comment]
Intentional Behaviour; closing

OWDrakes can only breed twice
