### ISSUE TITLE
My Sugar Glider Keeps Taking Damage From Nothing

### ISSUE THREAD

**Issue by CommandBlockGuru** [WolfShotz/Wyrmroost#115]
**Logs:** {Link(s) to GitHub Gist, Pastebin, etc with full latest.log and/or crash report}

**Steps to Reproduce:**
 1. Tame a creature
 2. Wait a bit
 3. The creature is already half dead great :)

**Description of issue:**
My poor sugar glider keeps getting injured from nothing. All I have to do is go to sleep or get it out of render distance and it's half dead. How do I fix this?

**Comment by WolfShotz** [comment]
Seems to be related to the health desync, refer to #117
