### ISSUE TITLE
Alpine Dragons Unbreedable in 1.16.3

### ISSUE THREAD

**Issue by IceaPlayzPC** [WolfShotz/Wyrmroost#118]
When i try to breed alpine dragons on version 1.2.4 for 1.16.3, nothing happens. They can be healed by honeycombs and honey bottles just fine but nothing happens when breeding them. I have ensured they are tamed before breeding them. Have tried switching worlds with no change.

things i tried:
-tried right clicking them with honeycombs or honey bottle while sitting and standing
-tried hitting the dragon and then healing it, then trying to click them again
-switching worlds
-full game restart
-using honey blocks or honeycomb blocks (didn't work, i just got on the dragons instead)

**Comment by Raptorlos** [comment]
did the alpines breed 4 times already? if so thats the problem

**Comment by IceaPlayzPC** [comment]
@Raptorlos nope. It wouldnt let me breed them at all.

**Comment by WolfShotz** [comment]
Could not reproduce.
