### ISSUE TITLE
1.16.3 eggs not hatching

### ISSUE THREAD

**Issue by TheJN101** [WolfShotz/Wyrmroost#121]
minecraft 1.16.3 the Canari egg and the one that takes 33min do not hatch (iam waiting for about two hours.... Canari should take 5min)

**Comment by TheJN101** [comment]
the others work fine

**Comment by TheJN101** [comment]
the other one is the butterfly leviathan

**Comment by Amazedmonster6** [comment]
You sure the egg meets all conditions before it can hatch?

**Comment by WolfShotz** [comment]
Canari Wyvern Eggs can only hatch on top of leaves

Buttetfly Leviathan Eggs can only hatch in water

**Comment by TheJN101** [comment]
ohhhhhhhhhhhhhh makes sence
