### ISSUE TITLE
Alpine dragons not tameable

### ISSUE THREAD

**Issue by hotwings1018** [WolfShotz/Wyrmroost#125]
Using the wiki guide, I tried to tame several alpine dragons with the pollinated bee attached to a lead (attempted multiple times in creative with different worlds, ensured the latest version etc.), however, the dragons ignore it entirely instead of attacking and killing the bee.

Please advise.

**Logs:** {Link(s) to GitHub Gist, Pastebin, etc with full latest.log and/or crash report}

**Steps to Reproduce:**
 1. Do this
 2. Then do that
 3. ...

**Description of issue:**

**Comment by WolfShotz** [comment]
YOU the player, needs to have the bee leashed. make sure the alpine eats it while still leashed to you. also next time, please join the discord if you have trouble
