### ISSUE TITLE
Pathfinding is slow; effectively slowing down servers. Most prominent in swimmers and flyers

### ISSUE THREAD

**Issue by SubkingExtinct** [WolfShotz/Wyrmroost#126]
I do not have a crash report to this issue since it didn't crash my game it's a minor issue but i suppose it could be of use for the team to fix.

  **Steps to reproduce**
It dosen't have a step other than the lag starts on the render distance
May or may not work that way, as far as i know every time i enter the area where my butterfly leviathan is, entities start moving slowly

**Description of issue:**
Mainly what appears to be server lag, entities moving slowly and ocassionally moving faster after a "lag spike" it is not frame rate, chest takes a little while to open when the butterfly leviathan is near, The lag dissappears once the leviathan has gone off the render distance, same thing happens with wild butterfly leviathans.

**Extra information**
These are the mods i've been using for the most part along WyrmRoost

![Captura de pantalla 2020-10-20 000013](https://user-images.githubusercontent.com/73154515/96542306-5d3ad400-1267-11eb-88b4-005a08d56703.jpg)

If you'd like more information contact me at aarnzv@gmail.com, thank you for your time Modders!

**Comment by WolfShotz** [comment]
This issue appears mostly actually in vanilla. One of the forge devs, and I quote "Screamed at Fry during a live stream to fucking fix it"
(Fry is a mojang dev, Fry was watching the stream). Though ill look into it to 👍
