### ISSUE TITLE
RR fire breath issues

### ISSUE THREAD

**Issue by Spinogaming** [WolfShotz/Wyrmroost#129]
I found two issues regarding RR fire breath
1. If a fire_breath entity has hit a block, it cannot hurt entities anymore. Imo all fire_breath entities should be damaging no matter what since it's weird to just phase through the fire unharmed
2. When you die by RR fire_breath, the death message is just "death.attack.fireBreath"

**Comment by LagoonTheAbyssal** [comment]
That second one certainly sounds appropriate for Wolf.

**Comment by WolfShotz** [comment]
fixed in 1.2.5
