### ISSUE TITLE
[CRASH-Repeating] DragonFollowOwnerGoal

### ISSUE THREAD

**Issue by Nachtflame** [WolfShotz/Wyrmroost#13]
https://pastebin.com/ij6QgQa6
https://pastebin.com/YpaaadVs

Title & Crash reports are pretty clear.

Mod v1.0.1
forge-28,1,10

**Comment by WolfShotz** [comment]
... I thought I tested this.. smh. Would u happen to catch any sorts of steps to reproduce?

**Comment by Nachtflame** [comment]
had him tamed, and apparently free-roaming.  he'd get a distance away, and boom-crash.

**Comment by Nachtflame** [comment]
was in the area with a group of them for over an hour before taming.  both crashes happened within 10mins of taming one.  No further crashes since getting him into a  Soul thingy...

**Comment by WolfShotz** [comment]
Hasnt been reproduced in v1.0.2, Closing.
