### ISSUE TITLE
Drakes vibrate

### ISSUE THREAD

**Issue by ADHDemon** [WolfShotz/Wyrmroost#132]
Spawned a few Overworld Drakes from spawn eggs in Creative and they just start vibrating. When I only had a single Drake, no vibrating, but as soon as another is nearby, they both begin to vibrate.

**Comment by WolfShotz** [comment]
update the mod

**Comment by ADHDemon** [comment]
To what version? I do not want to use 1.16 because my other mods are not updated for it yet.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by WolfShotz** [comment]
1.15 has a version that fixes it, use the latest 1.15 version

**Comment by ADHDemon** [comment]
Ok thank you very much, sorry for the trouble. I love the mod :)

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
