### ISSUE TITLE
[1.15.2] Terraforged incompatbility leading to crash

### ISSUE THREAD

**Issue by EightBlade** [WolfShotz/Wyrmroost#133]
It's as the title says, when generating a world with Terraforged I get the following crash when using Wyrmroost.

**Logs:** 
https://pastebin.com/4gXgRD2K

**Steps to Reproduce:**
 1. Install wyrmroost and terraforged
 2. Generate a world using terraforged
 3. Crash. Be sad.

**Description of issue:** See above.

**Comment by WolfShotz** [comment]
This is an issue with flexible skills, not wyrmroost. It seems that their "Tempting AI" does not support wyrmroost creatures. Is it possible to blacklist wyrmroost from the mod?
