### ISSUE TITLE
Server crashes on 1.16.3  1.2.6 when OWD tries to attack a player

### ISSUE THREAD

**Issue by j-1658** [WolfShotz/Wyrmroost#135]
**Logs:** {https://mclo.gs/NYJkL3B}

**Steps to Reproduce:**
 1. Start up a server with Wyrmroost
 2. Find an OWD
 3. Switch to survival if you were in a different mode
 4. Walk up to the OWD

**Description of issue: It is basically issue #119 but in the latest update. OWD make server go boom.**

**Comment by WolfShotz** [comment]
The log is invalid

**Comment by j-1658** [comment]
Sorry, it took me a second to figure out how to download it, does this one work: https://pastebin.com/Ma7X21v8

**Comment by WolfShotz** [comment]
yes it does, thank you

**Comment by pajakkox** [comment]
If OWD means overworld dragon, i've got the same problem, server is crashing when he tries to attack.

**Comment by Elliyos** [comment]
Also having this issue. Lots of mods on our server but the mods I share with @j-1658 are this one, Psi, AI Improvements, Mahou Tsukai, Patchouli, Quark, Quark Oddities, and Waystones.
