### ISSUE TITLE
Dragon homes being removed when ridden

### ISSUE THREAD

**Issue by ShinyDragon96** [WolfShotz/Wyrmroost#139]
When you ride a dragon, it will remove the dragon's home and in stead start following you. I have to go back and re-set it's home block every time I want to ride it.

**Comment by WolfShotz** [comment]
Intentional. What happens when u dismount your dragon in the middle of no where and it teleports back to it's home position?

**Comment by ShinyDragon96** [comment]
Ohh, I see. I just thought it would keep the home thing you you could like send it home.
