### ISSUE TITLE
Projectiles de-aggro royal red

### ISSUE THREAD

**Issue by GundunUkan** [WolfShotz/Wyrmroost#143]
Steps to Reproduce:
 1. Get a mob that shoots projectiles to fight a RR (can use Mob Battles mod for ease of testing)
 2. Watch

Shooting an aggroed RR with a projectile completely de-aggros it (not applicable to players). If a RR aggros a projectile shooting mob it de-aggros and will only hit once if it gets attacked first. 
Good mob to test this issue with: Dread Lich (Ice and Fire).

**Comment by WolfShotz** [comment]
Re-evaluate: does this happen with vanilla skeletons? (Give them resistance 10 so they live long enough) if not, this is a problem with other mods. They are not properly applying the damage source.

**Comment by GundunUkan** [comment]
I tested it with vanilla skeletons as well, gave them geode arrows so that they can actually shoot the RR. The answer is yes, it still happens. Fairly certain it's a RR bug.

**Comment by WolfShotz** [comment]
Doesn't make sense if it's fine for players..

**Comment by GundunUkan** [comment]
Try it for yourself.

**Comment by AwesomeMCRider** [comment]
I want to report bug. Baby BFL becomes extremely buggy and even loses his head (Litteraly!) It sometimes turns invisible as soon as i moved it into water pool:
![Uploading 2020-11-13_14.05.31.png…]()

**Comment by WolfShotz** [comment]
Could not reproduce (With vanilla skeletons)
