### ISSUE TITLE
Alpine Dragons Directional Control

### ISSUE THREAD

**Issue by DGuillotine** [WolfShotz/Wyrmroost#145]
**Logs:** {Link(s) to GitHub Gist, Pastebin, etc with full latest.log and/or crash report}

**Steps to Reproduce:**
 1. Do this
 2. Then do that
 3. ...

**Description of issue:**
I'm not sure whether or nor this was intentional or it's something you're planning to fix, however, it is near impossible to fly the alpine dragon now. It moves far too fast to be able to maneuver like before the latest two updates. Thank you very much for listening to my concerns and I wish you the best luck in further developing this mod!

**Comment by WolfShotz** [comment]
I plan on doing some control adjustments in the future.
