### ISSUE TITLE
drake causing players to crash on server

### ISSUE THREAD

**Issue by MoofMoofVan** [WolfShotz/Wyrmroost#146]
**Logs:** {Link(s) to GitHub Gist, Pastebin, etc with full latest.log and/or crash report}

**Steps to Reproduce:**
 1. Do this
 2. Then do that
 3. ...

**Description of issue:**
There's an issue that when our players get too close to the drakes on our server it causes the to crash. Right now we are advising people disable the mod until a diff. admin logs on to disable drakes specifically. 
[crash-2020-11-11_19.20.00-server.txt](https://github.com/WolfShotz/Wyrmroost/files/5526439/crash-2020-11-11_19.20.00-server.txt)

[crash-2020-11-11_19.20.00-server.txt](https://github.com/WolfShotz/Wyrmroost/files/5526436/crash-2020-11-11_19.20.00-server.txt)

**Comment by Tbear000** [comment]
This is the same as the previous OWD crashes Please disregard.

**Comment by WolfShotz** [comment]
Update the mod, this has been fixed.
