### ISSUE TITLE
Overspawning Issues

### ISSUE THREAD

**Issue by NovaKiit** [WolfShotz/Wyrmroost#147]
**Logs:** {Link(s) to GitHub Gist, Pastebin, etc with full latest.log and/or crash report}

**Steps to Reproduce:**
 1. Do this
 2. Then do that
 3. ...

**Description of issue:**
![2020-11-12_00 33 23](https://user-images.githubusercontent.com/74331124/98877086-eff21b80-247f-11eb-872c-d35ccb1e7c3e.png)
 
Many Drake families are spawned in the jungle, even once killed they come out again and again

**Comment by WhatTheBright** [comment]
I have the same problem. There are so many that it covers my entire minimap when I have the radar on. Had to remove the mod till this is fixed since I live in a biome they spawn in. >.<

**Comment by EightBlade** [comment]
Same problem here on 1.15.2
