### ISSUE TITLE
BFL's stop damaging

### ISSUE THREAD

**Issue by DailyDoseOfExtra** [WolfShotz/Wyrmroost#148]
**Logs:** {Link(s) to GitHub Gist, Pastebin, etc with full latest.log and/or crash report}

**Steps to Reproduce:**
Not sure if this is exactly how to since I could only do it once but 
 1. Spawn in a Butterfly Leviathan in creative 
 2. Go into survival and get bit
 3. Profit

**Description of issue:**
I got bit by a Butterfly Leviathan trying to tame it and I couldn't get hurt by them again.

**Comment by WolfShotz** [comment]
Peaceful?

**Comment by WolfShotz** [comment]
No response, and cannot seem to reproduce, assuming fixed.
