### ISSUE TITLE
Silver Glider + Riding a Drake = Crash instead of Glider Dismount

### ISSUE THREAD

**Issue by LagoonTheAbyssal** [WolfShotz/Wyrmroost#15]
Reported by AotuurLe.
https://pastebin.com/t4KPC5z6

**Comment by WolfShotz** [comment]
Elaborate.

**Comment by WolfShotz** [comment]
ok good catch, was able to reproduce. Thank u for the report.

**Comment by WolfShotz** [comment]
Turns out to be a duplicate of #13. Closing
