### ISSUE TITLE
Tamed Pets Teleportation Issues

### ISSUE THREAD

**Issue by Flamaxius952** [WolfShotz/Wyrmroost#150]
I noticed that when teleporting, tamed mobs often end up in a wall or in a space that's too small for them, and thus begin suffocating and eventually die. This is really frustrating when it comes to survival. One time an instance (Overworld Drake) even teleported in the air multiple times, kept on plummeting to the ground, over the span of a couple of seconds until it died. I don't really know how to reproduce this issue. It sorta happened randomly and I don't remember anything that could have potentially caused it.

**Comment by WolfShotz** [comment]
Cannot seem to reproduce.
