### ISSUE TITLE
Blame Reports: ConfiguredFeature Not Registered

### ISSUE THREAD

**Issue by Elliyos** [WolfShotz/Wyrmroost#152]
**Logs:** https://pastebin.com/FqnBDRMG (similar reports for wyrmroost:blue_geode_ore and wyrmroost:platinum_ore)

**Steps to Reproduce:**
 1. Install Wyrmroost on a server
 2. Run server
 3. Get error

**Description of issue:**
Error pops out as a Blame report. Might be worth looking into; Wyrmroost is causing some instability and this may be at the root of it.

**Comment by WolfShotz** [comment]
Sounds right. Registered Configured Features was considered optional as I was told back when I was working with this stuff. Thank you for the reminder

**Comment by TelepathicGrunt** [comment]
Gonna pop in and help explain why it needs to be registered and an example on how to do so:

Under certain conditions, unregistered ConfiguredFeatures can basically prevent other mod's registered ConfiguredFeatures from spawning if in the same generation stage.

If mod A adds an unregistered CF to the ore generation stage and the biome's codec reaches it first, it will choke and basically nuke mob B's registered CFs afterwards. Here's a case where BetterCaves forgot to register their CF and caused several CFs from Oh The Biomes You'll Go to stop spawning in the world: yungnickyoung/YUNGs-Better-Caves#75

Here's a more detailed explanation of why this happens in the biome's codec:
![image](https://user-images.githubusercontent.com/40846040/95459000-ff41ee80-0940-11eb-8569-52a2be15cc4d.png)

Specifically, when you call .withConfiguration on a Feature, you create a ConfiguredFeature. This is what should be registered to the WorldgenRegisties at mod init (you can do it in FMLCommonSetupEvent so you have your config ready too if it is needed). 

Anyway here's an example from my mod RepurposedStructures of me registering all my ConfiguredFeatures.
https://github.com/TelepathicGrunt/RepurposedStructures/blob/a4e3365e3867b8510952ebf658c415de6e412927/src/main/java/com/telepathicgrunt/repurposedstructures/RSConfiguredFeatures.java#L184-L185

I hope this helps!
