### ISSUE TITLE
Silver glider jump boost fall damage

### ISSUE THREAD

**Issue by internetidi0t** [WolfShotz/Wyrmroost#153]
Silver gliders can take damage when you land if you have enough of the jump boost effect applied
1. Give yourself jump boost
2. Pick up a silver glider
3. Jump
Only happens if the player has jump boost and the dragon does not.

**Comment by WolfShotz** [comment]
They take fall damage if the player does, all entities that ride others that take fall damage take the same damage. This is considered a MOJANG FEATURE, don't ask me why, but its intentional.
