### ISSUE TITLE
Server issues

### ISSUE THREAD

**Issue by Oppolzer** [WolfShotz/Wyrmroost#154]
Hello, I have a minecraft server with my custom mods on it and some of a dragons cause problems. My Red Royal can´t be feeded and when I get close to Overworld drake my server crashes. Maybe the other mods cause the problem I haven´t tested that yet, but if there is a way to improve the compatibility with other mods it would be great.
Thx for reading.

Bye

**Comment by WolfShotz** [comment]
The overworld drakes causing server crashes has been fixed with the latest version of the mod.

**Comment by Oppolzer** [comment]
Oh nice, so the only problem that´s left is that dragons on server don´t heal when I give them food (Red Royale, and Alpine as I found out).
Thank you for the info

**Comment by Oppolzer** [comment]
It´s like I give them the food and the food dissapiers from my hotbar, but it´s still in there (If I drop it it appears) and the dragon isn´t healed

**Comment by Oppolzer** [comment]
OK NEVERMIND... updating to new version fixed the issue as well
Thank you so much for help
