### ISSUE TITLE
Alpines Getting Stuck In Walls For No Reason

### ISSUE THREAD

**Issue by BrokenBlueSky** [WolfShotz/Wyrmroost#157]
**Logs:** Didn't make me crash, just annoying.

**Steps to Reproduce:**
 1. Push against wall (be it I push them, ride them into wall, or another dragon pushes them).
 2. Get stuck and start suffocating
 3. Soon die

**Description of issue:** Self explanatory, Alpine Dragons get stuck and suffocate in walls. I have them in a spacious cave, and yet they still get stuck.

**Comment by PerpetualToddler** [comment]
Sometimes they'll teleport to me or fly themselves into a wall and start suffocating

**Comment by WolfShotz** [comment]
I think I'd consider more of a minecraft bug. Its very inconsistent, and I can't seem to recreate it AS OF NOW on my side, thought I've seen it before in other mobs, not just wyrmroost ones. I am unaware of what *causes* this but im sure someone has tracked it down on Mojangs issue tracker somewhere.
