### ISSUE TITLE
Rooststalkers fail to enter love mode

### ISSUE THREAD

**Issue by smooze** [WolfShotz/Wyrmroost#160]
Steps to reproduce:
1. Give rooststalker a gold nugget
2. Give a second rooststalker a gold nugget.
3. Wait nearby with the chunk loaded
Description of  issue:
I have several rooststalkers holding gold nuggets in their mouths, and they are not entering love mode despite hanging out with them for hours they are still holding onto their gold.
I am running a multiplayer server with the following mods:

A Lib (by al132)
Abnormals Core API (by SmellyModder)
Absent by Design (by Lothrazar)
AI Improvements (by DarkGuardsman)
AIOT Botania (by MelanX)
Alchemistry (by al132)
AmbientSounds 3 (by CreativeMD)
Apotheosis (by Shadows_of_Fire)
AppleSkin (by squeek502)
Aquaculture 2 (by Shadowclaimer)
Archer's Paradox (by TeamCoFH)
Armor Toughness Bar (by tfarecnim)
Artifacts (by ochotonida)
Atmospheric (by paradiscal)
AutoRegLib (by Vazkii)
Autumnity (by martianarchitecture)
Back Tools (by ohaiiChun)
Bamboo Blocks (by bageldotjpg)
Bed Benefits (by DarkhaxDev)
Bedspreads (by TheIllusiveC4)
Better Advancements (by way2muchnoise)
Better Burning (by DarkhaxDev)
Better Title Screen (by Girafi)
Better Weather (by Corgi_Taco)
Biomes O' Plenty (by Forstride)
Blood Magic (by WayofTime)
Bones (by ochotonida)
Bookshelf (by DarkhaxDev)
Botania (by Vazkii)
Buzzier Bees (by bageldotjpg)
Caelus API (TheIllusiveC4)
CC: Tweaked (by SquidDev)
Chem Lib (by al132)
Cherished Worlds (by TheIllusiveC4)
Chisels & Bits (by AlgorithmX2)
Client Tweaks (by BlayTheNinth)
Cloth Config API (by shedaniel)
Clumps (by Jaredlll08)
Comforts (by TheIllusiveC4)
Controlling (by Jaredlll08)
Cooking for Blockheads (by BlayTheNinth)
Cosmetic Armor Reworked (by LainMI)
Crafting Tweaks (by BlayTheNinth)
Curio of Undying (by TheIllusiveC4)
Curios API (by TheIllusiveC4)
Curious Elytra (by TheIllusiveC4)
Curious Shulker Boxes (by TheIllusiveC4)
Dark Utilities (by DarkhaxDev)
Dash (by ModdingLegacy)
Decorative Blocks (by stohun)
Default Options (by BlayTheNinth)
Double Slabs (by CJMinecraft01)
Drawers Tooltip (by Snownee_)
Enchanted Book Redesign (by tfarecnim)
Engineer's Decor (by wilechaote)
Ensorcellation (by TeamCoFH)
Enhanced Mushrooms (by Ep1c312)
Extended Lights (by Polyvalord)
Extra Boats (by Markus1002)
Fairy Lights (by pau101)
Farmer's Delight (by vectorwing)
Farming for Blockheads (by BlayTheNinth)
Fast Leaf Decay (by olafskiii)
FastFurnace (by Shadows_of_Fire)
FastWorkbench (by Shadows_of_Fire)
Fishing Real (by PricelessKoala)
Flux Networks (by sonar_sonic)
Forbidden and Arcanus (by cesar_zorak)
Friendly Fire (by DarkhaxDev)
FTB Backups (by LatvianModder)
Goblin Traders (by MrCrayfish)
Hwyla (by TehNut)
iChunUtil API (by ohaiiChun)
Immersive Engineering (by BluSunrize)
Immersive Petroleum (by Flaxbeard)
Incubation (by Markus1002)
Industrial Foregoing (by Buuz135)
Inventory HUD+ (by dmitrylovin)
Inventory Sorter (by cpw)
Iron Chests (by ProgWML6)
JEI Enchantment Info (by Phylogeny)
JEI Integration (by SnowShock35)
Just Enough Items (by mezz)
Just Enough Resources (by way2muchnoise)
KubeJS (by LatvianModder)
Leap (by ModdingLegacy)
Light Overlay (by shedaniel)
Macaw's Bridges (by sketch_macaw)
Macaw's Doors (by sketch_macaw)
Macaw's Roofs (by sketch_macaw)
Macaw's Trapdoors (by sketch_macaw)
Macaw's Windows (by sketch_macaw)
Mekanism (by bradyaidanc)
Mekanism Additions (by bradyaidanc)
Mekanism Generators (by bradyaidanc)
Mekanism Tools (by bradyaidanc)
MineColonies (by H3lay)
Miner's Helmet (by ModdingLegacy)
Mouse Tweaks (by YaLTeR)
Nature's Compass (by Chaosyr)
Neapolitan (by bageldotjpg)
Neat (by Vazkii)
Neon Craft Mod (by Polyvalord)
Netherite Horse Armor Mod (by louie_cai)
OldJavaWarning (by DarkhaxDev)
Open Loader (by DarkhaxDev)
OpenBlocks Elevator (by vsngarcia)
Overloaded Armor Bar (by tfarecnim)
PackMenu (by Shadows_of_Fire)
Pam's HarvestCraft 2 - Crops (by pamharvestcraft)
Pam's HarvestCraft 2 - Food Core (by pamharvestcraft)
Pane In The Glass (by MongoTheElder)
Patchouli (by Vazkii)
Placebo API (by Shadows_of_Fire)
Polymorph (by TheIllusiveC4)
Powah! (by owmii)
Psi (by Vazkii)
Quark (by Vazkii)
Quark Oddities (by Vazkii)
RandomPatches (by TheRandomLabs)
ReAuth (by TechnicianLP)
Refined Storage (by raoulvdberge)
Refined Storage Addons (by raoulvdberge)
Reliquary (by P3pp3rF1y)
Runelic (by DarkhaxDev)
Savage & Ravage (by Farcr)
Scuba Gear (by ModdingLegacy)
Server Tab Info (by black_dog20)
ServerConfig Updater (by Darkere)
Simple Discord Rich Presence (by Sunekaer)
Snow Under Trees (by bl4ckscor3)
Spiders 2.0 (by TheCyberBrick)
Step (by ModdingLegacy)
Storage Drawers (by Texelsaur)
Structure Gel API (by ModdingLegacy)
Structurize (by H3lay)
SwingThroughGrass (by exidex)
Tetra (by mickelus)
The Mighty Architect (by simibubi)
The Conjurer (by ModdingLegacy)
The Endergetic Expansion (by endergized)
Titanium (by hrznstudio)
Toast Control (by Shadows_of_Fire)
Torch Slabs Mod (by EndlesNights)
Transport (by Sky_Som)
TrashSlot (by BlayTheNinth)
Upgrade Aquatic (by minecraftabnormals)
Valhelsia Structures (by ValhelsiaTeam)
Valhelsia Tweaks (by ValhelsiaTeam)
Waddles (by Girafi)
Waila Harvestability (by squeek502)
Waystones (by BlayTheNinth)
Worley's Caves (by super_fluke)
Wyrmroost (by Kingdomall)
Xaero's Minimap (by xaero96)
Xaero's World Map (by xaero96)
YUNG's Better Mineshafts (by YUNGNICKYOUNG)

**Comment by j-1658** [comment]
I have the same issue in the latest version with just Wyrmroost installed.

**Comment by KamikazePigeon** [comment]
I'm also having this issue with about 50 mods installed with the latest version of Forge/Wyrmroost. Dragon Fruit Drakes breed just fine, though, so it's strange.
