### ISSUE TITLE
Royal Reds only breeding once

### ISSUE THREAD

**Issue by Volvalex** [WolfShotz/Wyrmroost#161]
Heya, not sure if this is intentional or not, but upon taming a male and female Royal Red and breeding them, they seem to be unable to breed again. 

1. Tame a Male and Female Royal Red.
2. Feed them while they are standing.
3. They produce an egg.
4. Attempt to make them breed again later and they will not.

I have waited an entire day and tried periodically throughout the day and they still cannot breed, despite being able to be fed and getting the little hearts when I feed them. Alpines and Overworld Drakes seem to be able to breed multiple times without issue, though I haven't tried other dragons yet. I have tried putting them in Soul Crystals and bringing them back out. I have tried leaving render distance and waiting a long time to return. I have tried just literally waiting around with them in render distance. I have no other mods installed besides Wyrmroost.

**Comment by Dragonmatic** [comment]
You seem to have reached the breed limit, you would have to get a new pair of Royal Reds or go into your world>serverconfig folder and edit the wyrmroost-server.toml file to disable it.

**Comment by Volvalex** [comment]
Should I just delete the Breed Limits line in the .toml?

**Comment by WolfShotz** [comment]
Nah, just have the two square brackets (`[]`) empty

Intentional Behavior; closing
