### ISSUE TITLE
Canari wyvern eggs not hatching or emitting particles

### ISSUE THREAD

**Issue by Direbat** [WolfShotz/Wyrmroost#162]
![minecraft screenshot 1](https://user-images.githubusercontent.com/74643395/99639880-38a46880-2a6e-11eb-8e9a-18b89e0efbe9.png)

I am not sure weather this is a compatibility issue but in the picture you can see that the rooststalker eggs(on the right) are emitting yellow particles but the canari wyvern eggs(on the left) are not. This may be a compatibility issue but I do not have any mods that affect tick speed so I am not sure why they are not hatching even after leaving them for well past 5 minutes. 

Also the rooststalker eggs do hatch after 5 minutes so it seems to be a problem with just canari wyverns(but I have not tested all the types of dragon eggs yet)

**Comment by Direbat** [comment]
Also I am using 1.15.2 and the latest version of the mod

**Comment by VakyPanda** [comment]
Canai wyvern eggs need to be on leaves to hatch ( I think? It was jungle but Im not too sure )

**Comment by Direbat** [comment]
ok i will try that
