### ISSUE TITLE
Projectiles Crashing the game

### ISSUE THREAD

**Issue by Daejangnamu** [WolfShotz/Wyrmroost#163]
[crash-2020-11-19_19.51.03-server.txt](https://github.com/WolfShotz/Wyrmroost/files/5566513/crash-2020-11-19_19.51.03-server.txt)

Forge-1.16.4-35.0.1

**Comment by Daejangnamu** [comment]
Second problem: Too many desertwyrm are spawned.
![unknown](https://user-images.githubusercontent.com/52635462/99665791-72489400-2aad-11eb-85db-a917c2c55c3a.png)

**Comment by WolfShotz** [comment]
Please keep issues separate.

**Comment by WolfShotz** [comment]
Could not reproduce
