### ISSUE TITLE
[suggestion] Forge version

### ISSUE THREAD

**Issue by Tymogekh** [WolfShotz/Wyrmroost#165]
I made a server with wyrmroost and overlord drakes was crashing the game, so I ubdated mod to newer version, but this version requires forge version 34.1.35 which is crashing the game. Can you support forge version which is working?

**Comment by WolfShotz** [comment]
..the mod works fine with that version.. you also didn't send a crash report, as asked in the issue template; so I have 0 context on the situation.

**Comment by Tymogekh** [comment]
Sorry for my last not-in detail comment. So, there are other mods on this server and game crashes becouse of them, but I'm asking you becouse most mods are incompatible with this version. This issue is half-suggestion becouse I think, so it's not only my trouble and incompatibility is half issue too. I don't posted crash report becouse it's forge's trouble. If it's not very hard plase enable this mod work on stable versions of forge... If it is, you can close this discussion, sorry for making a trouble.

**Comment by WolfShotz** [comment]
The forge version is bare minimum lol. You can even use latest 1.16.4 version if you wanted to. The version on the mod is just the minimum
