### ISSUE TITLE
Tamed creatures

### ISSUE THREAD

**Issue by YT-Brawlertomi** [WolfShotz/Wyrmroost#166]
What i did
 1. Have a tamed creature on a dragon soul cirstal (royal red, or butterfly leviathan, atleast these was my pets)
 2. Dont join in the world after 1 day (or some time)
 3. Make the creature get out of the crystal (i did it on creative mode)

What happened exactly
i was going to travel on an ocean with my albino leviathan (female), when i put it out of the crystal, it was standing, i was able to ride it, but i wasnt able to move it. After that, i tryied with another leviathan, the dark purple variant (male) and a dark blue variant (female), this happened with both creatures. Then, i decided to try on my royal red (female), when i started to ride it, i wasnt able to fly with it, the creatures was like no-tamed but yes at the same time, all my creatures were sitting, but when you ride a domesticated creature it gets up and you can control it. The sad thing is it took me lots of hours to find an albino BL, also found, fight and tame the Rr 

Screenshots:

![2020-11-20_00 17 29](https://user-images.githubusercontent.com/74750673/99754004-42f25100-2ac6-11eb-971f-869772993ace.png)
![2020-11-20_00 19 59](https://user-images.githubusercontent.com/74750673/99754023-4980c880-2ac6-11eb-8458-cdc740091782.png)
![2020-11-20_00 20 24](https://user-images.githubusercontent.com/74750673/99754034-4f76a980-2ac6-11eb-84f3-074278e09ce5.png)

if they are tamed, i should be able to see the stats with the staff dragon, but it doesnt work. Also, when i ride it i should be able to look at the hearts of the creature

**Comment by WolfShotz** [comment]
The player that tamed them does not match the player that you provided the screenshot with. These are different accounts. This kind of thing happens a lot with cracked clients. You must use the account you used to tame those creatures, and if you used a cracked launcher you may be out of luck

**Comment by YT-Brawlertomi** [comment]
> The player that tamed them does not match the player that you provided the screenshot with. These are different accounts. This kind of thing happens a lot with cracked clients. You must use the account you used to tame those creatures, and if you used a cracked launcher you may be out of luck

thanks, im going to try with another account, i hope it works

**Comment by YT-Brawlertomi** [comment]
tysm, it works now

but i have a question:

i have 2 launchers, 1 where i can ride the dragons, and other launcher where i dont, can i make a launcher have the controls over the dragons? like, give the other account the creatures

i have TLauncher and Phoenix launcher (spanish launchers)

**Comment by WolfShotz** [comment]
Just have the launcher that isn't working use the account that tamed them.
