### ISSUE TITLE
Crashing most likely due to summoning with commands

### ISSUE THREAD

**Issue by punkrotts** [WolfShotz/Wyrmroost#169]
Good afternoon,

I've been experiencing issues when attempting to summon dragons with commands. The first time this happened, I tried to summon an Alpine, but the world crashed as soon as I pressed enter. When trying to visit the world, it immediately crashed again. After a few minutes of trying to get into the world, I decided to recreate the world again. This time, I attempted to summon a Canari Wyvern, but the same issue occurred. Both of the worlds are basically unplayable.

"The game crashed whilst rendering entity in world
Error: java.lang.ArrayIndexOutOfBoundsException: 10
Exit Code: -1"
[FailedToRenderEntityCrash.txt](https://github.com/WolfShotz/Wyrmroost/files/5580303/FailedToRenderEntityCrash.txt)

Minecraft 1.16.4
Forge 35.0.22

Hope this was helpful

**Comment by WolfShotz** [comment]
Canari Wyvers don't have 10 variant's, that's the problem
There is a limited amount of variants to dragons that have them. If those variants don't exist then the rendering throws a fit as there's no existing texture for it.
I'm working on a fail-safe for this but I'm not technically classifying this as a bug as it's working as intended
