### ISSUE TITLE
Hello Is there a way to make this Mod for 1.12.2

### ISSUE THREAD

**Issue by Drogash** [WolfShotz/Wyrmroost#17]
Hello I was Wondering if there was a easy way to make this Mod work for MineCraft 1.12.2

Right now im Playing RL Craft and i added some extra mods into. it to make it harder/ more fun

and i wanted to Add your Mod into MY RL Craft World. but when i did. it says i need minecraft 1.13

but if i updated to minecraft 1.13 none of my other mods i use will Work. so i was Hoping if there was a way for 1.12.2  I Would really Be Thankful if it could be done.

thanks for taking your time and reading my message.  Good Work on your Mod keep it up Sir!!

**Comment by Jceratops** [comment]
Read the discord's rules

**Comment by Jceratops** [comment]
They have made it very clear that they will not back port

**Comment by WolfShotz** [comment]
We will not be doing back ports under no circumstances. Nor, is there any way that you can make the mod function in newer/older versions of the game unless you code it yourself. Which I may add, isnt the easiest of tasks
