### ISSUE TITLE
BFL right headfin issue

### ISSUE THREAD

**Issue by Spinogaming** [WolfShotz/Wyrmroost#170]
BFL right headfin is a lot darker than the left headfin
![2020-11-24_09 09 10](https://user-images.githubusercontent.com/48093218/100037529-e4fe9a00-2e34-11eb-8f14-ddf177c6775d.png)

**Comment by WolfShotz** [comment]
model mirroring...? idk?? Assigning King

**Comment by Kingdomall** [comment]
I know of this. fin isn't mirrored.

**Comment by WolfShotz** [comment]
*still exists, leaving it open*
