### ISSUE TITLE
[Wyrmroost-1.16.4-1.2.7] Butterfly Leviathan does not leave post lightning strike state

### ISSUE THREAD

**Issue by apinkglaceon** [WolfShotz/Wyrmroost#174]
**Steps to Reproduce:**
1. Wait for butterfly leviathan to strike you with lightning
2. butterfly leviathan can no longer strike you again and can be fed indefinitely until tamed.

Tested using forge version 35.1.6

**Comment by WolfShotz** [comment]
Are you in creative mode...?

**Comment by WolfShotz** [comment]
Could not reproduce
