### ISSUE TITLE
Royal despawns instandly when put in nether

### ISSUE THREAD

**Issue by Ashiya69** [WolfShotz/Wyrmroost#180]
My friend had a royal red in this dragon ball where you can store your dragon. Then he went into the nether and released the dragon but disappeared shortly after and is nowhere to be found

**Comment by WolfShotz** [comment]
Could not reproduce

**Comment by Ashiya69** [comment]
How you mean could not reproduce?
I said nothing about mating
The royal despawned in the nether and is lost now
My question is why? Can dragons not be in the nether?

**Comment by WolfShotz** [comment]
I could not re-create your issue. You didn't necessarily provide steps for me to follow. So I assumed that it was basic "place soul crystal in nether and it is gone". They can be in the nether just fine, from what I'm seeing here.

**Comment by Ashiya69** [comment]
Then why did the Royal Red dissappeared? I would only believe it that dragons can be in the nether when there are pictures

**Comment by WolfShotz** [comment]
![image](https://user-images.githubusercontent.com/32242079/102702086-a63de300-422c-11eb-8dc1-790a3c99408d.png)

There's your picture. (Excuse the Christmas texture).

If you want your issue solved you need to provide me more information than just "I placed the crystal in nether and now it's gone." That gives me zero context. I ran tests based on what you gave me. and from that, I concluded that there is no issue.

**Comment by Ashiya69** [comment]
Idk what i should say to you. The dragon was stored in the soul crystal, enter the nether and used the crystal and it was there for a slight second but just was gone. I checked my home if it was spawned there but there was nothing

**Comment by Ashiya69** [comment]
And thanks for the picture

**Comment by VakyPanda** [comment]
Where was the dragon first picked up ( before disappearing ) using the soul crystal? Try going there and looking for it

**Comment by WolfShotz** [comment]
Should not matter. Positions are based on the world instance when used. The nether has its own world instance. IF ANYTHING, you need to go to the cords of that old position IN THE NETHER, if this was the case. However, I do not believe this would be the case (as of now)

**Comment by Ashiya69** [comment]
We did but he wasnt there

**Comment by VakyPanda** [comment]
Ah, i see
