### ISSUE TITLE
Royal Red Legs

### ISSUE THREAD

**Issue by jaesunn** [WolfShotz/Wyrmroost#181]
This isn't really a bug but more of a visual thing. When royal red fly and stop mid air, their legs remain in a position where it looks like it's moving. Instead of going down when you stop riding the dragon, the leg stay perked up instead of resting down.
https://imgur.com/a/xMMDTCb
I posted 3 images on imgur if you don't get what im trying to say. First imagine is the royal red's legs perking up even though it's not moving. Second shows an example of an ice and fire dragon when it's flying and it makes it's legs go up and the 3rd shows it staying still mid air with it's legs down.

**Comment by Spinogaming** [comment]
Hovering positions are planned
