### ISSUE TITLE
Saddle Disappears on Drake - 1.14.4

### ISSUE THREAD

**Issue by Ocatora** [WolfShotz/Wyrmroost#185]
Here's a quick summary of the issue. 
 1. Put a saddle on a tamed overworld drake. 
 2. It works, leave world and exit game.
 3. Log back into world.
 4. Saddle has disappeared.

Basically, every time I leave the world, saddles on tamed overworld drakes disappear. A small issue, but would be nice to have resolved. Thank you. This is 1.14.4.

**Comment by WolfShotz** [comment]
1.14 is not supported anymore. This issue has been fixed in the newer versions
