### ISSUE TITLE
Reminder for Wolf to rename DFD's _s textures to _spe

### ISSUE THREAD

**Issue by Spinogaming** [WolfShotz/Wyrmroost#187]
Rename the _s textures to _spe because _s = specular map which makes them shiny with a shader that has PBR materials

**Comment by WolfShotz** [comment]
I hate shaders!

**Comment by Spinogaming** [comment]
Why were the DFD special textures _s anyway when the other special textures were _spe?

**Comment by WolfShotz** [comment]
Because I stay up way too late developing this mod
