### ISSUE TITLE
If you ride someone else's drake, you're stuck on it. Also animation glitch.

### ISSUE THREAD

**Issue by TRCI101** [WolfShotz/Wyrmroost#19]
Me: *Walks up to someone else's drake and mounts it*

Drake: "Hey, you aren't my friend!"

Me: "Well I can be your friend to yknow."

Drake: "Oh really? Well then if you want to be friends so badly, with the power of FLEX SEAL you are now stuck with me forever!"

Me: "Wait wha-. HEY I CANT GET OFF"

*Owner of drake arrives*
Owner: "Oh shit, did he use flex seal on you?"

Me: "Sadly yes."

Owner: "Ok, usually making it sit works." *Makes the drake sit*

Drake: "I'm not done yet! With the power of breaking all know laws of science, I can run around while sitting, and I've put even more Flex Seal! 

Owner and I: "That's a lot of damage!"

Summary: Sitting on someone else's drake will remove the ability to dismount. If the owner makes the drake sit with you on it, then animation breaks. You can still run around with the drake, but it'll be in the sitting animation rather than running.

**Comment by WolfShotz** [comment]
In my defense I cant really test multiplayer in that sense. (Cant run two client instances)
As for that.. *what the hell*
Unable to dismount? I wish I knew what controlled dismounting. As Im using vanilla mechanics on that one. Will look into it...

**Comment by Kingdomall** [comment]
Closing because it's unrepeatable and no one else has reported this. If we get one more report we'll look into it further. Thanks for the report though.
