### ISSUE TITLE
Server crash when mods check if dragon has valid mate

### ISSUE THREAD

**Issue by WenXin20** [WolfShotz/Wyrmroost#196]
`Minecraft v1.16.4`
`Forge v35.1.15`
`Wyrmroost v1.2.10`
[`Pokecube AIO v3.5.0`](https://www.curseforge.com/minecraft/mc-mods/pokecube-aoi)

**Logs:**
[Crash Report](https://gist.github.com/WenXin20/1043ad38469a3513e6848c243e08d3bb)

**Steps to Reproduce:**
 1. Find the `pokecube-server.toml` file in the serverconfig folder.
 2. Change both `non_vanilla_pokemobs` and `vanilla_pokemobs` to true.
 3. Find a Roost Stalker
 4. Crash

**Description of issue:**
The server crashes when another mod checks for a dragon's valid mate. In my case, it happened with Pokecube AIO if the config is changed to allow for non-vanilla pokemobs.

**Comment by Thutmose** [comment]
I will add in an exception handling on my end, but this side should probably check if the cast is valid here:

https://github.com/WolfShotz/Wyrmroost/blob/master/src/main/java/com/github/wolfshotz/wyrmroost/entities/dragon/AbstractDragonEntity.java#L861-L868

Vanilla behaviour checks if the `mate` is the same class, before further processing.

**Comment by WolfShotz** [comment]
In my defense, I did not add any further checks since my custom breeding goal does this already. Though I will say I was not thinking very "comparability" wise. Will fix this.
