### ISSUE TITLE
first there is a bug my royal red keep spamming same attack and second my alpine keeps disappearing mid air then it does not return

### ISSUE THREAD

**Issue by uygaronaterol** [WolfShotz/Wyrmroost#198]
**Logs:** {Link(s) to GitHub Gist, Pastebin, etc with full latest.log and/or crash report}

**Steps to Reproduce:**
 1. Do this
 2. Then do that
 3. ...

**Description of issue:**

**Comment by WolfShotz** [comment]
First, make separate issues for... separate unrelated issues... please.
Second, RR doesn't spam attacks it uses fire breath, that's what it does.
Third, disappearing issue has been fixed in the latest version.
