### ISSUE TITLE
Ore Tag Request

### ISSUE THREAD

**Issue by Syrikal** [WolfShotz/Wyrmroost#199]
**Description of issue:**

When using the Better End mod, caves in the end generate with floating Purple Geode ore. The mod dev says that this is because the caves only replace end stone and blocks in the Forge ORES tag. Could you tag the geodes as ore?

Thanks!

**Comment by WolfShotz** [comment]
sure thing!
sorry for overlooking this.

As for a temp solution, u could make a datapack to add purple geodes to add it to the ores tag.

**Comment by WolfShotz** [comment]
Fixed in 3353f647dcfd676ac3ead9559289ab318e994250
