### ISSUE TITLE
If killed by pillagers or ravagers, a drake ressurects

### ISSUE THREAD

**Issue by TRCI101** [WolfShotz/Wyrmroost#20]
Pillager: "Oh a player on a drake? Let us kill his mount, brothers!"
 *Pillagers and Ravagers tear the drake apart*

Drake (In the afterlife): "Oh shit, Im ded. This isn't allowed, my friend is probably getting destroyed up there! I must go back and finish what we started!" 
*Drake begins chanting spells*

Back in the Overworld:

Player: "Damn there's to many of them, at this rate the village will be overridden!"

Drake's spirit: "HA I'VE COMEBACK FUCKERS" *Spirit drake begins yeeting every pillager and ravager in the underworld*

Summary: When killed by pillagers and ravagers, dead drake manifests into spirit drake, with no model, and attacks everything.

**Comment by WolfShotz** [comment]
Everything u report is the most bizarre shit ive ever seen. Ill look into this when I get time, however I doubt this can be reproduced .-.

**Comment by qnebra** [comment]
Very poetic and fun, but provide at least list of mods you are using.

**Comment by TRCI101** [comment]
The first time was with a couple of other mods for a server. However I don't need to say those since I tried it out with only wyrmroost, and it still happened.

**Comment by TRCI101** [comment]
Assume every bug I've posted so far has been tested with only wyrmroost (which I have been)

**Comment by WolfShotz** [comment]
Does this occur on servers only?

**Comment by TRCI101** [comment]
Managed to get it working on sp once, but that was it

**Comment by WolfShotz** [comment]
Cannot recreate this in SP, I'll test this further in MP when I get time.

**Comment by WolfShotz** [comment]
Could never recreate
