### ISSUE TITLE
Tamed Butterfly Leviathan doesn't summon lightning.

### ISSUE THREAD

**Issue by BrokenValkyrie** [WolfShotz/Wyrmroost#201]
Minecraft version: 1.16.3/1.16.4
Forge version: 1.16.3 - 34.1.42 / 1.16.4 -35.1.28
Wyrmroost version: 1.2.10

I tested this on 1.16.3 and 1.16.4. Wild one can still summon lightning on player. Tamed Butterfly Leviathan can't summon lightning when ordered to. I've checked the keybinding and tested only with wyrmoost mod. It will play the animation, roar and the light pattern dims but nothing happen.

Tested on various hostile mobs, while in water or during rain on land. Only attempted it once the light pattern return. Nothing shows up on log.

**Comment by BrokenValkyrie** [comment]
I remember it working a while back. I tried version wyrmroost version: 1.2.7 and it worked again.

**Comment by Carro1001** [comment]
I can assure you it summons lightning as i died to one instantly because of it in the latest version

**Comment by Carro1001** [comment]
My bad i didn't see it was an issue with tamed ones

**Comment by GundunUkan** [comment]
The leviathan summons lightning only when targeted at an entity, otherwise it does nothing. Try this.

**Comment by BrokenValkyrie** [comment]
Late response but I did try to target hostile entity. The animation won't play unless I target a hostile entity, when it does no lightning is summoned.

**Comment by leily00** [comment]
I have same problem in 1.16.4，when I press the skill button and catch the enemy，she just does an actionwithout thunder.
