### ISSUE TITLE
Royal reds crash clients on lan worlds

### ISSUE THREAD

**Issue by dianamonde** [WolfShotz/Wyrmroost#202]
**Log**
https://pastebin.pl/view/71644459

**Steps to Reproduce:**
 1. Tame a royal red on a lan world
 2. Client rides a royal red
 3. Server player lags a bit, client is disconnectable

**Description of issue:** When a client rides a royal red on a lan world, it will make the server player have a lag spike and when its over the client will be disconnected.

**Comment by WolfShotz** [comment]
Can you remove a mod called "spartan shields" and try to recreate this?
Wyrmroost seems to be unrelated, but I want to make sure.

**Comment by WolfShotz** [comment]
Going off the assumption that this is related to #177
