### ISSUE TITLE
Dragons have 0 IQ and decide that their home position is a fence.

### ISSUE THREAD

**Issue by Therzis** [WolfShotz/Wyrmroost#205]
**Logs:**
 no logs :sad:

**Steps to Reproduce:**
 **Bug 1:**
  1. Leash a dragon to a fence
  2. Tame the thing
  3. Oh no, an issue.
  
 **Bug 2:**
  1. Leash a dragon
  2. Fly high
  3. Unleash the dragon
  4. Enjoy your cheap infinite Portal loop but with no portals

**Description of issue:**
 **Bug 1:**
 When taming a dragon that has been leashed to a fence, the dragon thinks that the fence is its home position (they don't follow you and some dragons go back to the fence if they get too far). You can walk/fly some dragons out of the bug, but some can only get out of it by making them target a mob using the target command and/or removing their home position.
  **Bug 2:**
 When any dragon is unleashed in mid-air, it starts teleporting to the place it was unleashed. Some tamed dragons can get out of the loop by removing their home position, but not all so they have to be flown out of it or use the target command. Untamed dragons have to step on a block to get out of it.
 
_**Note:** The use of crystals and breaking the fence hasn't been tested._

**Video showing the bugs:**
 https://www.youtube.com/watch?v=VnV3VVfeJFk

**Comment by WolfShotz** [comment]
mmm yes. fence post portals
