### ISSUE TITLE
Crash when jumping on Royal Red with Create

### ISSUE THREAD

**Issue by BirgerBrun** [WolfShotz/Wyrmroost#207]
**Logs:** Crash Log: https://pastebin.com/vy9Ygeaj
              Latest Log: https://pastebin.com/qgE9cXCE

**Steps to Reproduce:**
 1. Create a profile with Forge 35.1.36
 2. Install Wyrmroost and Create, the latest versions as of January 10th
 3. Create a world and tame a Royal Red or Alpine
 4. Get on him and wait around 1-2min
 5. Crash

**Description of issue:** Crash to desktop after taming and riding Royal Red Dragon or Alpine

**Comment by VakyPanda** [comment]
I have experienced this issue too

**Comment by BirgerBrun** [comment]
> 
> 
> I have experienced this issue too

And is it only with Create for you too?

**Comment by VakyPanda** [comment]
with other mods, but create _was_ present

**Comment by WolfShotz** [comment]
This seems to be an issue on creates end, specifically talked about [here](https://github.com/Creators-of-Create/Create/issues/669)
