### ISSUE TITLE
Game crashed when using dragon staff on Alpine

### ISSUE THREAD

**Issue by EloinPugaFlores** [WolfShotz/Wyrmroost#208]
whenever i use a staff on my alpine dragon my game crashes. although I have not tested if it does the same with other dragons.

**Comment by WolfShotz** [comment]
Game logs? Crash logs? Anything? I can't do much with only that context... :/

**Comment by Just-Jam** [comment]
Are you using shaders? I've also encountered this issue, but only when using shaders.

**Comment by GundunUkan** [comment]
In case you are using shaders -threre is a config option to disable the custom dragon staff shader that causes an incompatibility crash with most other shaders.
