### ISSUE TITLE
All my Silver Gliders got suffocated by a wall.

### ISSUE THREAD

**Issue by Bluniverse** [WolfShotz/Wyrmroost#212]
**Logs:** {Link(s) to GitHub Gist, Pastebin, etc with full latest.log and/or crash report}

**Steps to Reproduce:**
 1. Tame a Silder Glider
 2. Let it fly a little
 3. Boom! It just got suffocated by a wall.

**Description of issue:**
Everytime i tamed a Silver Glider, after a while the dragon got suffocated by a wall. It happened more than one time. The dragon was just flying around, then it happened. I wasn't inside of a cave or anything, just walking outside.
That was the only dragon specie i tamed.

**Comment by WolfShotz** [comment]
Could not reproduce.
