### ISSUE TITLE
Dragons dont spawn on my world

### ISSUE THREAD

**Issue by Goryloco** [WolfShotz/Wyrmroost#213]
**Logs:** {Link(s) to GitHub Gist, Pastebin, etc with full latest.log and/or crash report}

**Steps to Reproduce:**
 1. Do this
 2. Then do that
 3. ...

**Description of issue:**
In my world i puted the mod but the mobs arent spawning, if i creat a new world they spawn on that world so whats is the problem on my current world, the world that im playing was created before installing the mod

**Comment by GundunUkan** [comment]
The dragons spawn on chunk generation, meaning that any chunks generated previously will not spawn any dragons. You can find dragons if you go in previously unexplored areas, do keep in mind some dragons are pretty rare tho.

**Comment by Goryloco** [comment]
can i make them spawn in those chunks somehow?

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Libre
de virus. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
