### ISSUE TITLE
NullPointerException - In combination with Ice and Fire Mod

### ISSUE THREAD

**Issue by Maruhl** [WolfShotz/Wyrmroost#214]
**Logs:** {Link(s) to GitHub Gist, Pastebin, etc with full latest.log and/or crash report}
[crash-2021-01-18_15.27.05-client.txt](https://github.com/WolfShotz/Wyrmroost/files/5830813/crash-2021-01-18_15.27.05-client.txt)

**Steps to Reproduce:**
 The log is attached. I cannot describe the error that precisely. It seems to happen in relation with the mod 'Ice and Fire'. When the entities with a Gorgon head are turned to stone.

When the error occurs, it is no longer possible to continue playing.

**Description of issue:**
Game crashes completly.

**Comment by WolfShotz** [comment]
This is a problem on ice and fire's side. The "entity" that's passed into the rendering for me to work with is not whats normally to be expected, to put it simply. I work with Minecraft's normal procedures, ice and fire makes that common procedure weird.
