### ISSUE TITLE
All of my dragons are stuck in sprinting mode and my alphine is too fast to control

### ISSUE THREAD

**Issue by Anna66501** [WolfShotz/Wyrmroost#215]
**Logs:** {Link(s) to GitHub Gist, Pastebin, etc with full latest.log and/or crash report}

**Steps to Reproduce:**
 1. Do this
 2. Then do that
 3. ...

**Description of issue:**

**Comment by WolfShotz** [comment]
These are intentional.

All dragons have a "Turn Radius", which means it takes time for them to rotate to fly in that direction. It's there for a better feeling flight than just the dragon turning immediately in one direction or stopping immediately as soon as the movement keys are let go
