### ISSUE TITLE
The alpine summoning glitch, is there a solution

### ISSUE THREAD

**Issue by Kyoayder** [WolfShotz/Wyrmroost#216]
**Logs:** {Link(s) to GitHub Gist, Pastebin, etc with full latest.log and/or crash report}

**Steps to Reproduce:**
 1. I’m pretty sure everyone knows the problem and how to reproduce it.
 

**Description of issue:**
Is, is there a solution to this? As I’m in a mc server and I summoned it without knowing it’ll crash my game and never let me back in without saying “Saved world” and crashing, but for everyone else the world works perfectly fine. I’m running out of options here, and I want to play on the server again. Yk?

**Comment by WolfShotz** [comment]
I have no idea what this summoning glitch is and its the first im hearing about it. What are you talking about?

**Comment by Kyoayder** [comment]
the uhh when you try to summon a variant -1 alpine, the game’ll crash but before that it’ll simply say “saved world” and stuff.

**Comment by WolfShotz** [comment]
The only solution is that you need to remove the entity from the world's region files. That, or you change your player nbt data and change your position.

**Comment by Kyoayder** [comment]
I unfortunately don’t know how to do that :[ any of that :[

**Comment by WolfShotz** [comment]
Give this forum a shot: https://gaming.stackexchange.com/questions/359445/how-do-i-delete-an-entity-from-the-minecraft-world-folder
