### ISSUE TITLE
Tamed dragons attacked

### ISSUE THREAD

**Issue by ShiftingRaptor** [WolfShotz/Wyrmroost#218]
**Logs:** {Link(s) to GitHub Gist, Pastebin, etc with full latest.log and/or crash report}

**Steps to Reproduce:**
 1. Do this
 2. Then do that
 3. ...

**Description of issue:**
Okay so I've been playing with the mod for a while I first started playing it at 1.1.2 and I just now managed to install the [1.16.3+] Wyrmroost 1.2.11. I jumped on to play it I had to make a backup of the world I was playing since it was with a old version of the mod I had to find my way back to my house because I was out in the forest on my last save. I have one Overworld Drake, two Canary wyverns, one butterfly Leviathan in a small pond, a few silver gliders and a Rooststalker the moment I got close the butterfly Leviathan it attacked me and then I was immediately attacked by my Overworld Drake. So I'm trying to figure out how to make them recognize me again.

**Comment by WolfShotz** [comment]
Your using a different account. You used a different account to tame those dragons, and now they don't recognize you. Either that, or your experiencing #243
