### ISSUE TITLE
Platinum Chestplate Crash

### ISSUE THREAD

**Issue by OllieZone** [WolfShotz/Wyrmroost#221]
When me or my friends wear a Platinum Chestplate (wyrmroost:platinum_chestplate) the game crashes. I use Forge 1.16.3 34.1.43.

**Comment by LagoonTheAbyssal** [comment]
You need to provide more info, developers cannot magically know what's causing the crash without a crash report or log file. Please send one so your issue can be looked into properly.

**Comment by OllieZone** [comment]
I think this is the crash log of platinum chestplate: [crash-2021-01-27_18.54.39-client.txt](https://github.com/WolfShotz/Wyrmroost/files/5885598/crash-2021-01-27_18.54.39-client.txt)

**Comment by WolfShotz** [comment]
You have a corrupted jar file, please redownload on curseforge
