### ISSUE TITLE
Royal Red Fire Breath Crash

### ISSUE THREAD

**Issue by lartts** [WolfShotz/Wyrmroost#223]
Royal Red breath crashes when it hits an endermite on a singleplayer world
[latest.log](https://github.com/WolfShotz/Wyrmroost/files/5887521/latest.log)
[crash-2021-01-28_20.32.24-server.txt](https://github.com/WolfShotz/Wyrmroost/files/5887526/crash-2021-01-28_20.32.24-server.txt)

**Comment by WolfShotz** [comment]
You are using an extremely old version. Ive fixed this in newer versions.
