### ISSUE TITLE
Dragon Staff Freezing Screen with specific shader

### ISSUE THREAD

**Issue by Hukenon** [WolfShotz/Wyrmroost#225]
1. Use Dragon Staff using BSLex
2. Screen freezes.
NOTE: I believe it has something to do with the glow effect added to tamed dragons linked to staff. I've tried with SILDURS Extreme and BSLex and can only produce issue with BSLex. Its quite a nice shader, so for the time being I'll just switch it off to name dragons :)
I also don't know what other shaders have issues, so I can't say for sureif  it's ONLY BSLex, which is why I'm leaving this here.

**Comment by LagoonTheAbyssal** [comment]
I'm going to assume this is a clone of #176. Please go into your config, open "wyrmroost-cliient" and disable the dragon staff shaders. If it still freezes then that would be optifine/shaders fault, not Wyrmroost's.
