### ISSUE TITLE
1.16.4, fed 4 eggs to a rooststalker. doesn't tame????

### ISSUE THREAD

**Issue by acquaintedFowl** [WolfShotz/Wyrmroost#232]
**Logs:** {Link(s) to GitHub Gist, Pastebin, etc with full latest.log and/or crash report}

**Steps to Reproduce:**
 1. Do this
 2. Then do that
 3. ...

**Description of issue:**

**Comment by GundunUkan** [comment]
Not a bug. Roost stalkers take 1-10 eggs to tame, however a dragon egg (doesn't matter what dragon) is an instant tame. Keep feeding it.

**Comment by acquaintedFowl** [comment]
problem is i just tested it in creative, spawned in 5 roost stalkers - 2 of them needed one dragon egg, one of them needed 14, and sorry i wasn't specific (when i said egg i meant dragon egg)

**Comment by WolfShotz** [comment]
Actually it doesn't matter what egg it is the taming effectiveness is the same. (The dragon egg thing will be a feature later). As for now, roost stalkers have a 1 in 4 chance to tame if you feed it any egg. (Includes modded ones)

**Comment by GundunUkan** [comment]
Huh, I guess I remember the dragon egg being an instatame from an older version. I'm pretty sure it used to be a thing since I used to test it and it was always an instatame.
