### ISSUE TITLE
[Suggestion] Butterfly leviathans guard shipwrecks

### ISSUE THREAD

**Issue by MarioSMB** [WolfShotz/Wyrmroost#239]
This issue is mainly addressing the overpopulation of butterfly leviathans in the ocean; rather than randomly appearing anywhere, perhaps a single butterfly leviathan could be spawned around most shipwrecks, implying they were the cause for the ships going down and acting as a guard for the ship's loot.

EDIT: I'd like to note that they could still spawn randomly throughout the ocean (albeit at a greatly reduced rate), just far more frequently around shipwrecks.

**Comment by WolfShotz** [comment]
For future reference, please try to avoid suggesting features on the issue tracker. I use this to organize issues in the mod. You CAN however suggest new ideas in our discord! That way you can get almost immediate feedback as well. You can find an invite on the mod page or in the readme for this repo.
