### ISSUE TITLE
Platinum Armor Layers

### ISSUE THREAD

**Issue by UnableTugBoat** [WolfShotz/Wyrmroost#245]
![image](https://user-images.githubusercontent.com/79768409/109400025-5af42f00-7957-11eb-92b3-5ee535c4fe21.png)

(Using optifine G7, Minecraft 1.16.5)

I can't see platinum armor layers in game, i am playing with my two friends and they can see the layers while i can't and there is no mods installed that might get in the way. We have all use optifines and it might not be the problem cause they can see and i can't. Tried to use texturepacks and re-download the mod but didn't work at all.

**Comment by WolfShotz** [comment]
Have you tried redownloading the jar?

**Comment by WolfShotz** [comment]
Isn't reproducible, and has gone without response for nearly a month. Closing.
