### ISSUE TITLE
[1.16.5] Idle Butterfly Leviathans sink

### ISSUE THREAD

**Issue by MarioSMB** [WolfShotz/Wyrmroost#247]
**Logs:** {Link(s) to GitHub Gist, Pastebin, etc with full latest.log and/or crash report}

**Steps to Reproduce:**

**Description of issue:**
When staying still while riding the Butterfly Leviathan, it will start to sink slowly in the water. It would be nice if they remained at the same height.

**Comment by WolfShotz** [comment]
This is intentional behavior. They sink much like any other aquatic creature in the game when not moving.

**Comment by MarioSMB** [comment]
The issue here is that idling even for a few seconds on the leviathan means drowning, unlike with a boat which stays at the same depth (i.e. surface level). I'll bring this up on the Discord if preferred, but it seems like a design flaw to not stay floating on the surface of water.

Intentional or not, I hope this issue can be reconsidered, as it would improve the leviathan riding experience.
