### ISSUE TITLE
i added the mod to a modpack on curseforge and it isnt showing up, are there any mods it doesnt work with?

### ISSUE THREAD

**Issue by swaggysiah** [WolfShotz/Wyrmroost#251]
**Logs:** {Link(s) to GitHub Gist, Pastebin, etc with full latest.log and/or crash report}

**Steps to Reproduce:**
 1. Do this
 2. Then do that
 3. ...

**Description of issue:**

**Comment by KamikazePigeon** [comment]
Have you checked the mods folder/started up a game? There's a weird bug with overwolf/curseforge's app where sometimes a mod or several don't visually show up on the list but they still work just fine.

**Comment by WolfShotz** [comment]
Double check you actually have the mod installed in your pack
