### ISSUE TITLE
Invis dragons and other things when using dragon staff.

### ISSUE THREAD

**Issue by aluunzui** [WolfShotz/Wyrmroost#258]
**Steps to Reproduce:**
 1. Have optifine installed
 2. Turn on the internal shaders
 3. use dragon staff on any dragon thing
 4. hold dragon staff
 
Description: When looking at certain angles, things will disappear. It includes things like clouds, banners, and other things. It only appears when your holding it.

Example: https://youtu.be/sTxJLJhZLCw

**Comment by WolfShotz** [comment]
The staff renders a glow around dragons which shaders sometimes breaks. You can disable the glow in the client config for the mod.
