### ISSUE TITLE
Butterfly Leviathan seems to have crashed the server.

### ISSUE THREAD

**Issue by Guardian9978** [WolfShotz/Wyrmroost#268]
**Logs:** {Link(s) to GitHub Gist, Pastebin, etc with full latest.log and/or crash report}
https://pastebin.com/LfXPicRw

**Steps to Reproduce:**
 1. Unknown

**Description of issue:**
None of the creatures from the mod have been tamed.

Server crashed randomly and this mod seems to be the first thing I saw listed in the crashlog.
Line 24 in the log.

**Comment by WolfShotz** [comment]
Duplicate of #177
