### ISSUE TITLE
World not loading in

### ISSUE THREAD

**Issue by DogResidue** [WolfShotz/Wyrmroost#27]
When I have this mod installed, my world renders all the mobs at once and then one block at a time very slowly. When I remove the mod, this stops and everything loads instantly.
![2019-10-07_15 54 01](https://user-images.githubusercontent.com/32424783/66344627-55d6b000-e91c-11e9-97a6-a1044cefded8.png)
![2019-10-07_15 54 28](https://user-images.githubusercontent.com/32424783/66344628-55d6b000-e91c-11e9-9722-360e068c993b.png)
![2019-10-07_15 54 55](https://user-images.githubusercontent.com/32424783/66344629-55d6b000-e91c-11e9-8829-46242ca991be.png)

**Comment by WolfShotz** [comment]
This looks like a rendering problem.. Please specify: Is optifine installed? How about any game logs? And are u *sure* its Wyrmroost. Try all your mods with and without Wyrmroost installed.

**Comment by WolfShotz** [comment]
This has been left open with no reply for >15 days. Im going to assume the issue no longer persists and this was an issue on your end.
