### ISSUE TITLE
alpine drake male wont spawn ive spwaned in egg and all it spawns in females only

### ISSUE THREAD

**Issue by kopeckwarlock** [WolfShotz/Wyrmroost#271]
**Logs:** {Link(s) to GitHub Gist, Pastebin, etc with full latest.log and/or crash report}

**Steps to Reproduce:**
 1. Do this
 2. Then do that
 3. ...

**Description of issue:**

**Comment by WolfShotz** [comment]
Alpines do not have genders currently...
