### ISSUE TITLE
Please add a config option for SpawnRate of the Dragons

### ISSUE THREAD

**Issue by Camawama** [WolfShotz/Wyrmroost#275]
**Logs:** {Link(s) to GitHub Gist, Pastebin, etc with full latest.log and/or crash report}

**Steps to Reproduce:**
Play on the world, notice that the Butterfly Leviathan Spawns too frequently (in my opinion)

**Description of issue:**
I am currently working on a modpack and really wanted to add your mod. When I was playing with the mod installed, I noticed that the spawn rate for the Butterfly Leviathan was pretty high. I want certain things to be difficult to find on the modpack so I was just wondering if you guys plan on adding a config option in the future for spawnrate, and if not, would you be able to? Thank you for your time. The mod is amazing and I look forward to incorporating it into my modpack.

**Comment by WolfShotz** [comment]
please make suggestions in our discord. Not in the place where bugs are tracked.

I will look into config-related spawning later. So far have been having issues getting biome-related shit to correlate well with configs.
