### ISSUE TITLE
Suggestions on flight control mode of dragon riding

### ISSUE THREAD

**Issue by C-Zking** [WolfShotz/Wyrmroost#279]
I have a suggestion. Maybe when riding a dragon, the mouse should not control the ascending and descending. The mouse only controls the left and right rotation of the dragon, while the ascending and descending should be controlled by two separate buttons, just like ice and fire. In that case, when I fly in the sky, I can enjoy the scenery freely without causing control confusion.

**Comment by FelisGamerus** [comment]
For future notice, I'm pretty sure this is for issues, not suggestions. As for the actual suggestion, I believe that flight controls will be tweaked in the Revamp Update, which is the update after the current one that the devs are working on.
