### ISSUE TITLE
canari wyverns egg isn’t hatching

### ISSUE THREAD

**Issue by FluxxNeon** [WolfShotz/Wyrmroost#280]
**Logs:** {Link(s) to GitHub Gist, Pastebin, etc with full latest.log and/or crash report}

every time i put down the canari egg there are no particles and the hatching time doesn’t go down even though it has been there for more then 5 minutes of me being next to it i don’t know if there is a certain way to get this to work or if it’s bugged but i hope it can be fixed

**Comment by WolfShotz** [comment]
They hatch on top of jungle leaves, this is intentional behavior.
