### ISSUE TITLE
One hit kill and inventory deletion

### ISSUE THREAD

**Issue by NamacoFr** [WolfShotz/Wyrmroost#288]
So I play a heavily modded minecraft and got some issue with the mobs of Wyrmroost. I identified some aspect of the issue but basically upon spawning some beast will kill me in one hit whatever health and armor I have upon that death my whole inventory disappear in the void.

Even if pretty rare those bugged spawn already happened around 10 times and are pretty annoying. I do understand that maybe it's another mod that is maybe conflicting but none the less I'll report it just in case.

I also have a health bar indicator and have found that those bugged mobs show a max health of 0 despite having a normal amount of HP.

I must also precise that not all mobs are bugged only a selected few, for example over 10 butterfly drake there will be 1 that is bugged.

And by the way that mod is amazing so keep the hard work.

**Comment by WolfShotz** [comment]
yeah this sounds like a problem with your modpack. Wyrmroost creatures won't one tap you unless it's the royal reds bite and you have absolutely no armor.
