### ISSUE TITLE
Config Option for World Gen (Ores)

### ISSUE THREAD

**Issue by Traverse-Joe** [WolfShotz/Wyrmroost#291]
**Logs:** {Link(s) to GitHub Gist, Pastebin, etc with full latest.log and/or crash report}

**Steps to Reproduce:**
 1. Launch Mod
 2. Ores Spawn
 3. No Config.

**I would like a config option available to be able to set the spawnrate/disable ores. :**

**Comment by WolfShotz** [comment]
Please do not make suggestions in the ISSUES, I use this to track problems with the mod. If you have requests please join the discord and ask them there.

As for this, In order for me allow both sides of the spectrum (datapacks etc) and to help retain the CORRECT way of registering features like ores into the overworld, this system is gonna take time for me to think about how to go about it.
