### ISSUE TITLE
I think my drake eggs and arrows have ripped a hole in spacetime.

### ISSUE THREAD

**Issue by CyanKoopa** [WolfShotz/Wyrmroost#31]
A pillager patrol showed up, and i had my drakes stand up to fight it, The pillagers fired arrows at the drake eggs and instead of doing damage, they started having a seizure while floating at the side of the drake eggs.
![2019-10-19_22 16 02_2](https://user-images.githubusercontent.com/56775053/67152005-d42c3e00-f29c-11e9-804a-005f3762e408.png)
![2019-10-19_22 16 02](https://user-images.githubusercontent.com/56775053/67152006-d7272e80-f29c-11e9-9f10-a5a872d32408.png)
![2019-10-19_22 16 01_2](https://user-images.githubusercontent.com/56775053/67152010-da221f00-f29c-11e9-8271-671ae053471b.png)

**Comment by Kingdomall** [comment]
This is a tile entity so they won't take damage. We'll make sure that the eggs drop in the next update.
