### ISSUE TITLE
Young overworld drakes are tamed for free

### ISSUE THREAD

**Issue by slard3** [WolfShotz/Wyrmroost#32]
I just noticed a bug after a while hatching drake eggs. Feeding them wheat shows the particles, sounds and in the end, it tames them. But the drakes don't consume any wheat in the process.

I tried to look if there was an issue mentioning this before but I didn't find any, not even on the official discord.
EDIT: Worth mentioning I tried this with a lot of mods, but I can't recall any that should affect this behaviour

**Comment by CyanKoopa** [comment]
I've actually been having this too, i just haven't mentioned it.

**Comment by Kingdomall** [comment]
This will be fixed in the upcoming version. Thanks.
