### ISSUE TITLE
Blastfurnace issue, should be easy to fix.

### ISSUE THREAD

**Issue by CyanKoopa** [WolfShotz/Wyrmroost#34]
Platinum can't be used in the blast furnace, And geode ore doesn't work in the furnace at all.

**Comment by Jceratops** [comment]
Drake meat cant be smoked

**Comment by WolfShotz** [comment]
"Should be easy to fix." - Go ahead and make a PR for me then 😄

**Comment by CyanKoopa** [comment]
Alright, let me just go learn craft tweaker.

**Comment by WolfShotz** [comment]
zenScript =/= java u cuck
