### ISSUE TITLE
A bunch of issues regarding tamed dragons

### ISSUE THREAD

**Issue by slard3** [WolfShotz/Wyrmroost#40]
How to: I attack my tamed Overworld Drake. My tamed wolf will attack it too. The tamed Overworld Drake will stop following me (also won't teleport to me) and start to move against the wolf, spamming its attack animation, never actually hurting the wolf.  The drake would eventually stop grinding against the dog when is told to sit or is trapped inside a Soul Crystal.

**Comment by slard3** [comment]
Another issue regarding the Overworld Drakes. When a tamed drake follows me, I'm at a distance just below its teleport range and there's also lava between us, the drake will stupidly swim in lava to get to me.

**Comment by slard3** [comment]
Another issue regarding the Overworld Drakes. When a tamed drake follows me, I'm at a distance just below its teleport range and there's lava between us, the drake will swim in lava to get to me.
This is most easily to reproduce when the drake following me goes through water, since water slows it so much. (So, the drake falls into water, I move away from it across lava, and the drake will try to swim in lava to reach me).

**Comment by WolfShotz** [comment]
One, Future Notice: Please try to keep different issues in separate posts.
Second: Dragon Follow AI has been revamped in dev and this issue has been resolved already. Thank you for the report.
