### ISSUE TITLE
[CRASH] NPE: Ticking Entity - RoostStalker

### ISSUE THREAD

**Issue by Nachtflame** [WolfShotz/Wyrmroost#42]
Player was hatching ~~an~~ _multiple_ Egg_s_ inside the Nomadic Tent dimension.  Had stepped away when presumably, the egg Hatched.  Returned to GameCrash with following report- https://pastebin.com/ii33Jfzh

_3 eggs were obtained from Creative menu, other 2 apparently hatched just fine._

Wyrmroost-1.14.4-1,0,2
citadel-1.0.0
forge-28.1.87
NomadicTents-1.14.4-10.0.2-beta

**Comment by WolfShotz** [comment]
Problem has been resolved in development builds. Thank you for the report.
