### ISSUE TITLE
 the game crashes when I place an egg of one of the dragons, I guess it is due to some incompatibility with other mods, here I leave the crash report

### ISSUE THREAD

**Issue by ENERGIUM** [WolfShotz/Wyrmroost#43]
[crash-2019-11-17_23.20.13-client.txt](https://github.com/WolfShotz/Wyrmroost/files/3856569/crash-2019-11-17_23.20.13-client.txt)

**Comment by WolfShotz** [comment]
Your mod list is fine. Wyrmroost is at complete fault here, no clashes with other mods. Ignore my sh** code. Try to avoid opening the world with one placed if u can.
I've recently fixed this issue however and the egg actually functions as it should now.
Thanks for the report regardless.
