### ISSUE TITLE
Cannot hit a mob with sword

### ISSUE THREAD

**Issue by slowiu06** [WolfShotz/Wyrmroost#44]
Wyrmroost alone works good, but one of my mods makes impossible to hit Overworld Drake and RoostStalker with swords and other close-range weapons when bows works fine. I tried to remove some mods and find myself a bad guy but I had no luck. I haven't seen this problem occuring with mobs from other mods.

AdvancedSkinCustomization-2.6.jar
AppleSkin-mc1.14.4-forge-1.0.12.jar  
Aquaculture-1.14.4-2.0.2.jar
AutoRegLib-1.4-35.jar 
betteranimals-1.14.4-5.2.1.jar 
betteranimalsplus-1.14.4-7.1.2.jar
BetterThanMending-1.3.2.jar 
bettertridentreturn-1.14.4-1.0.0.jar 
betterwithminecolonies-1.14.4-1.8.9.jar 
BiomesOPlenty-1.14.4-9.0.0.258-universal.jar  
BirdsNestsAndTreasures-1.14.4-1.0.0.jar 
blockdrops-1.14.4-1.0.2.jar 
caelus-FORGE-1.14.4-1.0.1.1.jar
Charm-1.14.4-1.4.1.jar
citadel-1.0.0.jar  
CleanView-1.14.4-v1.jar  
Controlling-5.0.4.jar 
corail_woodcutter-1.0.6-1.14.4.jar
CraftingTweaks_1.14.4-10.1.4.jar  
CraftTweaker-1.14.4-5.0.1.140.jar 
Craft_and_Hunt_V0.9.3_MC_1.14.4.jar  
create-mc1.14.4_v0.1.1a.jar 
curios-FORGE-1.14.4-1.0.5.3.jar
curiouselytra-FORGE-1.14.4-1.0.jar
dankstorage-1.13.jar  
demagnetize-1.14.4-1.2.1.jar  
dogwhistle-1.0.jar 
DungeonCrawl-1.14.4-1.5.2.jar  
Durability101-1.14-0.0.3.jar
earthmobsmod-1.14.4-0.1.0.4-Beta.jar 
easyelytrato_1.14-1.1.jar
enchantedbookredesign-1.1.jar  
engineerstools-1.14.4-1.0.4-b2.jar
EnigmaticLegacy-1.6.2.jar
extcaves-1.3.3.jar 
Fast Tool Switching-1.14.4-1.0.0.jar 
FastFurnace-1.14.4-2.2.4.jar
FastLeafDecay-v17.jar 
FastWorkbench-1.14.4-2.1.4.jar 
Fence Jumper-1.14.4-1.0.8.jar  
ffenchants-1.14.4-1.2.2.jar  
forbidden_arcanus-1.14.4-1.5-beta-1.jar 
GoodSkeletonsDontStrafe-v1.1.1-1.14.4.jar  
goprone-1.14.x-1.1.0.jar 
horsemodifiers-1.1.2.jar 
hotdrop-1.14.4-1.0.jar
ironchest-1.14.4-9.1.5.jar  
ItemsDontBreak-1.14.4-0.3.jar  
jei-1.14.4-6.0.0.25.jar  
JustEnoughResources-1.14.4-0.10.0.66.jar
Ma-Enchants-1.14.4-1.5.1.jar
mgui-1.14.4-1.0.1.jar 
Mine and Slash Auto Compatibility-1.3.11.jar  
Mine and Slash-1.14.4-2.9.3.jar
minecolonies-0.10.559-ALPHA-universal.jar  
moblocks-0.6d.jar  
MouseTweaks-2.12-mc1.14.4.jar  
moveplus-1.14.4-2.4.6.jar
mysticallib-1.14.4-1.8.0.jar
nethercraft-1.14.4-1.0.3.jar
nhacampfire_1.14-1.5.jar 
OreExcavation-1.6.145.jar
pandoras_creatures-1.14.4-0.11.0.jar 
PickUpNotifier-v1.0.3-1.14.4.jar  
Placebo-1.14.4-2.3.5.jar 
PrettyBeaches_1.14.4-3.0.7.jar 
Quark-r2.0-199.jar 
randompatches-1.14.4-1.19.1.1.jar 
recycler-1.0.0.jar 
ResourcefulTools-1.14.4-1.0.4.jar 
respawnablepets-1.0.5.1.jar 
rsgauges-1.14.4-1.1.9-b2.jar
ScreenshotToClipboard-1.14.4-1.0.3.jar  
Server Utils-1.14.4-1.0.0.jar  
simplefarming-1.14.4-1.2.2.jar 
SimpleStorageNetwork-1.14.4-0.1.0.jar
skeletonhs_1.14-1.1.2.jar
SpartanShields-1.14.4-2.0.0.jar
speedyhoppers-1.14.4-7.jar  
structurize-0.10.199-ALPHA.jar 
Temporary Spawners-1.14.4-1.0.0.jar  
tetra-1.14.4-1.0.4.jar
The-Endergetic-Expansion-1.14.4-v1.0.jar
theoneprobe-1.14-1.4.37.jar 
thirdpersonelytra-1.14.4v1.2.jar  
ToolBelt-1.14.4-1.12.5.jar  
TrashSlot_1.14.4-10.4.7.jar 
travel_bag-1.0.6-1.14.4.jar 
traverse-1.14.4-2.0.1.jar.disabled
Upgrade Aquatic Wave Three v6 - Beta 1.0.8.jar
vilnames_1.14-1.4.jar 
WitherSkeletonTweaks-1.14.4-3.1.0.jar
wsw_1.14-1.2.jar
Wyrmroost-1.14.4-1.0.2.jar  
XaerosWorldMap_1.5.0.1_Forge_1.14.4.jar 
Xaeros_Minimap_1.18.9_Forge_1.14.4.jar  
Zmod 1.14.4-1.01.jar

**Comment by WolfShotz** [comment]
Just like you say, this is another mod, or ur setup causing this. Wyrmroost doesnt seem to be at fault here. If u insist, reopen the issue and I’ll look further into it.
