### ISSUE TITLE
debug log spam

### ISSUE THREAD

**Issue by Terpo** [WolfShotz/Wyrmroost#46]
[25Dez2019 14:01:30.882] [Client thread/INFO] [STDOUT/]: [WolfShotz.Wyrmroost.event.EventHandler$Client:ridingPerspective:121]: Fired

This is part of your latest release and causes more than 100.000 lines of log in a few minutes:
https://github.com/WolfShotz/Wyrmroost/blob/master/src/main/java/WolfShotz/Wyrmroost/event/EventHandler.java#L121

**Comment by WolfShotz** [comment]
If your using latest forge yes it will. However, this event never fired when this version of wyrmroost was released. This issue has been resolved in dev and thank you for the report.

**Comment by WolfShotz** [comment]
Additionally, if u wish to avoid this problems now, you can use an older version of forge

**Comment by Terpo** [comment]
No, I cloned it locally and removed the line myself ;).

**Comment by kreezxil** [comment]
I see you got this fixed so no need to report players reporting it to me. but I see there really is a fix that wasn't mentioned that resolves it somewhat.

Players only notice this issue if they have the console log on or open. So the actual solution until release is turn off the console log.
