### ISSUE TITLE
eta? on new releases?

### ISSUE THREAD

**Issue by kreezxil** [WolfShotz/Wyrmroost#47]
I noticed that citadel a library you depend on has updated 3 times since  you released wyrmroost.

I've further noticed you mentioned that things have been fixed in dev since then.

Might I suggest not waiting  to release mega loads of content like your predecessor did but instead to make a release frequently, at least once a month, or at least when you've fixed something.

Before you get mad as hell, I just donate to you, I believe in this project. I'm the World of Dragons - A New Age pack dev, in fact I'm the World of Dragons, pack dev, all variants.

**Comment by WolfShotz** [comment]
First of all, this sort of thing was more fit for the Discord. make further discussions about it there. this is NOT an issue/bug related to the mod. also why the hell would u make *two*, only to reference the original post? dont bump shit in github ESPECIALLY after *one minute*.
Second, yes citadel has updated 3 times, but this was in a matter of 1-2 weeks
Third, This next update will be big and then the rest after that won't be as large, and shouldnt take nearly as long.
There will be no ETA's, ever.
We appreciate the donation however. I can assure you things are getting worked on. If u have further questions, put it in the discord :facedesk:
*That goes for everyone*
