### ISSUE TITLE
Wyrmroost wont start

### ISSUE THREAD

**Issue by CaptainFoxx** [WolfShotz/Wyrmroost#49]
Trying to experience this mod so I downloaded it and Citadel and attempted to run Minecraft.  Came back in an error saying the mod requires Citadel version 1.0.0, I was using Citadel version 1.0.3.

I replaced Citadel with the requested version and the mod gave me a new error stating that Wyrmroost has encountered an error during the common_setup event phase.

[latest.log](https://github.com/WolfShotz/Wyrmroost/files/4175443/latest.log)

Attached is a copy of my log file. using Minecraft version 1.14.4 and Forge version 28.2.0

Is there other mods I need to run this with besides Citadel?

**Comment by Kingdomall** [comment]
The problem is that you're running latest Forge. Run recommended Forge and that will fix your problem.
_Always_ try to run recommended unless you absolutely have to do latest.
Our mod hasn't been updated in awhile because we're hard at work working on our next big update.
