### ISSUE TITLE
swim sleeping wild silver glider

### ISSUE THREAD

**Issue by Robomnz** [WolfShotz/Wyrmroost#51]
![2020-03-31_20 09 05](https://user-images.githubusercontent.com/34904608/77997772-755f0a80-738c-11ea-88d0-d5ea427e4af2.png)
caught this guy just sleeping and swimming at the same time i seriously dont think thats supposed to happen

**Comment by WolfShotz** [comment]
Hey congratz ur right. I havent got a feccing clue how u managed to pull this off but ill look into it

**Comment by Kingdomall** [comment]
I'm aware of this glitch, I thought it was beautiful considering that silver gliders could use their wings to stay afloat from predators on the land compared to over the water

**Comment by CodaBear1552** [comment]
*Bethesda intensifies*

**Comment by WolfShotz** [comment]
Probably fixed with new sleeping handling
