### ISSUE TITLE
right clicking a lesset desert wyrm makes the game go boom

### ISSUE THREAD

**Issue by aycfes** [WolfShotz/Wyrmroost#55]
[crash-2020-05-06_05.26.18-client.txt](https://github.com/WolfShotz/Wyrmroost/files/4585601/crash-2020-05-06_05.26.18-client.txt)

**Steps to Reproduce:**
 1.title

**Description of issue:**
title²

**Comment by WolfShotz** [comment]
Other mod problem, not mine. Tell them to handle NBT reading the right way.
