### ISSUE TITLE
Missing Saddle

### ISSUE THREAD

**Issue by arudon** [WolfShotz/Wyrmroost#60]
**Logs:** {Link(s) to GitHub Gist, Pastebin, etc with full latest.log and/or crash report}

**Steps to Reproduce:**
 1. So, first off launch the game using 1.14.4. 
 2. Then tame an Overworld Drake using the saddle method.
 3. Log out of the game 
 4. Log back into the world
 5. The saddle will no longer be on the Overworld Drake, regardless of whether or not you were on 
     it when you logged out. 

**Description of issue:**

The saddle on my Overworld Drake keeps dissapearing every time I exit back to the main menu and then log back into the world. It's pretty aggravating. The Drake remains tamed, and all I need to do is slap another saddle on him to ride him again, but the saddle is supposed to stay on regardless of whatever happens.

**Comment by WolfShotz** [comment]
[!] Affecting 1.14 - 1.15 versions.

**Comment by WolfShotz** [comment]
Cause: Saddles are set in the inventory client side.  Should only be done on the server
