### ISSUE TITLE
Unable to release any dragon from a soul crystal once the fail message appears no matter the condition

### ISSUE THREAD

**Issue by Dragonmatic** [WolfShotz/Wyrmroost#61]
![2020-05-13_15 21 20](https://user-images.githubusercontent.com/16492750/81811516-6fcd1680-952d-11ea-9119-fe022ae9b64e.png)

**Comment by WolfShotz** [comment]
Steps to reproduce are...?

**Comment by Dragonmatic** [comment]
Trying to release it in an invalid spot until the message appears, after that you are no longer able to
