### ISSUE TITLE
Dragons fail to target players/entities unless you're a server operator (Multiplayer)

### ISSUE THREAD

**Issue by LagoonTheAbyssal** [WolfShotz/Wyrmroost#63]
**Logs:** N/A
**Steps to Reproduce:**
 1. Attempt to target player/entity as regular player
 2. Fail
 3. Attempt to target player/entity as server operator
 4. Succeed
 5. ????
 6. Profitn't.

**Description of issue:** Tamed dragons seem to fail to target animals AND players unless their owner is a server operator.

**Comment by WolfShotz** [comment]
Could not reproduce.
