### ISSUE TITLE
[Suggestion] Shoulder Pets.

### ISSUE THREAD

**Issue by AlpZz80** [WolfShotz/Wyrmroost#65]
There's few mobs that we can get on our head as a pet.
Is there a way to get them on the shoulder using the parrot position or smth like that ?

Would be more interesting, and more aesthetics.
I hope it's not that hard if you manage to go for it.

Btw, your mods is insane, keep it up the great work !

**Comment by WolfShotz** [comment]
u can get the roost stalker and the canari wyvern on your shoulders, just interact with them as one is already on your shoulders ez

Github issues is made for issues to btw, nerd. Suggestions bad
