### ISSUE TITLE
crashing is like gravity all it takes is a little push from the blight RNG

### ISSUE THREAD

**Issue by slard3** [WolfShotz/Wyrmroost#66]
Wyrmroost-1.1.2
ScalingHealth-1.15.2-3.0.6+53
SilentLib-1.15.2-4.6.1+49

Minecraft: 1.15.2
Forge: 31.1.98

**Logs:** 
[Crash report here](https://gist.github.com/slard3/bd5fd9ad12b03274d2099907672acdce)

Second time it happens, I start a world, the game crashes when one Rooststalker tries to be a Blight. Right now ScalingHealth's blight blacklist isn't working (their issue #272) but I hope it gets fixed soon.
But my question actually is why rooststalkers like to crash my game? I can't see the reason behind their mysterious ways

**Comment by WolfShotz** [comment]
Wouldn't just be rooststalkers as the method is coming directly from the abstract dragon class
`func_184186_bw`
Line : `930`
*potentially* my fault, no promises tho. will look into it

**Comment by WolfShotz** [comment]
yeah, my fault. Casting without checking
