### ISSUE TITLE
Special Canari Wyverns are missing a texture if summoned with NBT

### ISSUE THREAD

**Issue by TheMinecraftOverlordYT** [WolfShotz/Wyrmroost#67]
**Logs:** {Link(s) to GitHub Gist, Pastebin, etc with full latest.log and/or crash report}
[https://imgur.com/a/gou0qbo](url)

**Steps to Reproduce:**
 /summon wyrmroost:canari_wyvern ~ ~ ~ {Variant:[any int that's not 1 or 0]}

**Description of issue:**
This might be due to the fact that the variants depend on name tags, but the wyvern just has a missing texture. This doesn't happen with any other dragons - if they don't have any special variant such as albino the regular texture just displays normally, no matter what int I pass.

**Comment by WolfShotz** [comment]
That is intentional.
