### ISSUE TITLE
Wyrmroost 0.1 Official Bug Report #1

### ISSUE THREAD

**Issue by Kingdomall** [WolfShotz/Wyrmroost#7]
Flight is alright and it really looks like it's gliding.
I figured since you only have animations to do this would be a good time to report some good ol' bugs.

1. ~~This is situational but it appears that breeding makes the female teleport. I believe this has something to do with the player eating fish while trying to feed it to the dragons. The dragon does not disappear however; you can use /tp @e[type=wyrmroost:silver_glider] @p to bring it back. If you can't replicate this in creative or survival then you don't have to worry about this.~~
[Couldn't Reproduce]

2. ~~Sometimes my sitting silver gliders will glitch for a brief moment. I think this is because of the animation.~~ [Couldn't Reproduce, if it keeps happening, report it again >.>]

3. ~~[UPDATED ISSUE] Silver Gliders struggle to take off while under blocks. In this specific case it was under glass, however I can't be sure if it does the same thing under other blocks.~~

4. ~~[Reminder] Rooststalker AI is a bit bugged. Caused by: several or more tamed rooststalkers holding geode swords. Only one or two would attack at a time and even then most of the time they were just jumping towards the target and not inflicting damage.~~ [Rare? Seems to be a vanilla bug when it happens sadly... won't fix]

5. ~~Silver Gliders do not have a baby stage.~~

6. ~~Hatched silver gliders will not be tamed to the player.~~[Intentional]

7. ~~[Reminder] Silver Gliders do not respect leads and will break them upon liftoff.~~

That's all the notes I have so far. These bugs aren't really that bad so take your time fixing them.
**_Good work Wolf~! We're all proud of you!_**

**Comment by WolfShotz** [comment]
1) Couldnt Reproduce
2) Couldnt Reproduce, Keep trying next time, if it happens again, report it >.>
3) Have a check for "Safe Flight" (Dont take off if blocks above it are present)
4) Vanilla bug, cant seem to get a workaround :c
5) tis done 👏
6) Was intentional
7) Wont take off if leashed
