### ISSUE TITLE
I am unable to open my dragons inventory and I cant make my dragons stay in one spot.

### ISSUE THREAD

**Issue by DinoKopi** [WolfShotz/Wyrmroost#70]
**Logs:** {Link(s) to GitHub Gist, Pastebin, etc with full latest.log and/or crash report}

**Steps to Reproduce:**
 1. Do this
 2. Then do that
 3. ...

**Description of issue:**

**Comment by Kingdomall** [comment]
please give us more details.

**Comment by WolfShotz** [comment]
so this was like, 2 months ago... annnd u didnt get back to us. This is now a *you* problem, goodnight!
