### ISSUE TITLE
Spawn Rate issues

### ISSUE THREAD

**Issue by belathus** [WolfShotz/Wyrmroost#74]
**Logs:** {Link(s) to GitHub Gist, Pastebin, etc with full latest.log and/or crash report}
Just pointing out that the kill command targeting lesser desertwyrms killed 975 of them.

![2020-06-14_18 38 01](https://user-images.githubusercontent.com/3826783/84605819-4ece4d00-ae6e-11ea-8731-35b51979e5a3.png)

**Steps to Reproduce:**
 1. Live in a desert.
 2. Stay online for a while...
 3. Watch your FPS die as more and more lesser desertwyrms spawn.

**Description of issue:**
They just keep spawning. It might take a while, but after being in my base for a day, I started noticing that they were everywhere. The 975 number is on a server, and I know at least one other player chose to base in a desert as well.

**Comment by WolfShotz** [comment]
This also applies to Butterfly leviathans.

**Comment by katubug** [comment]
And Dragonfruit Drakes. We have 276 in our server's currently loaded chunks.

**Comment by WolfShotz** [comment]
Fixed in 1.1.3
