### ISSUE TITLE
Crashed: Due to dragon staff

### ISSUE THREAD

**Issue by Spinoyonyx** [WolfShotz/Wyrmroost#75]
[crash-2020-06-16_22.19.06-client.txt](https://github.com/WolfShotz/Wyrmroost/files/4787221/crash-2020-06-16_22.19.06-client.txt)

[crash-2020-06-16_22.13.01-client.txt](https://github.com/WolfShotz/Wyrmroost/files/4787226/crash-2020-06-16_22.13.01-client.txt)

I am getting constantly crashed seems like it is due to the dragon staff

**Comment by WolfShotz** [comment]
Fixed in 1.1.3
