### ISSUE TITLE
[1.15.2] Server Crash on Butterfly Pathfinding

### ISSUE THREAD

**Issue by mr-poyo** [WolfShotz/Wyrmroost#76]
Version:  Wyrmroost-1.1.2.jar

Forge: 31.2.20

**Logs:** {Link(s) to GitHub Gist, Pastebin, etc with full latest.log and/or crash report}
crash log: https://pastebin.com/88NnUUEZ

**Steps to Reproduce:**
 1. Load mod into server
 2. Play normally for a few hours
 3. Wait for server to hang.
 4. After timing out, check server crash log.

**Description of issue:**
I have a server with a custom mod pack that has Wyrmroost. We are recently getting a crash whenever a certain player logs in. The crash report looks like he might be near a wyrmroost entity with some AI problem.

**Comment by WolfShotz** [comment]
src: Butterfly Leviathan Pathfinding

**Comment by denireilly** [comment]
i experience this too

**Comment by WolfShotz** [comment]
Fixed in 1.1.3
