### ISSUE TITLE
[QUESTION] Im looking for the 1.12.2 version, where's that?

### ISSUE THREAD

**Issue by ThisIsACoolBoy** [WolfShotz/Wyrmroost#79]
Not an issue but a question, where is 1.12.2 mod of this so I can put dragons in my 1.12.2 world?

**Comment by WolfShotz** [comment]
- Please do not ask questions here. I use github issues to track *issues*, it is disorganized and bugs won’t be fixed if I was lenient with that
- Secondly, there isnt, and wont ever be a 1.12 version. 1.12 is dying, I recommend you move on

**Comment by ThisIsACoolBoy** [comment]
oh ok
