### ISSUE TITLE
Gliding with two Silver Gliders produces unexpected behavior.

### ISSUE THREAD

**Issue by Verbina29** [WolfShotz/Wyrmroost#81]
**Logs:** [latest.log](https://github.com/WolfShotz/Wyrmroost/files/4928131/latest.log)

**Steps to Reproduce:**
 1. Tame two or more Silver Gliders.
 2. Put them on your shoulders.
 3. Attempt to glide.

**Description of issue:**
Gliding with more than one Silver Glider produces unexpected behavior. Instead of behaving similarly to Elytra, it instead only goes forward, straight up, or down.

**Comment by Kingdomall** [comment]
we are aware of this. next version should have it fixed.
