### ISSUE TITLE
laying down animations on drakes are broken

### ISSUE THREAD

**Issue by Robomnz** [WolfShotz/Wyrmroost#83]
when you make an overworld drake lay down 3 of its legs go into the ground while 1 front leg actually works

![image](https://user-images.githubusercontent.com/34904608/87843997-d8a98400-c90c-11ea-9988-5867b4bf5df3.png)
how to replicate: just make an overworld drake lay down

**Comment by Kingdomall** [comment]
yes we know, it's getting fixed
