### ISSUE TITLE
asking for permission 

### ISSUE THREAD

**Issue by MiahDragon** [WolfShotz/Wyrmroost#85]
this isn't an issue but i am looking for permission to use dragon mounts 2 code which i believe is the mod you created. i am making a mod which is a lot like dragon mounts but also very different. i just want permission to use the dragon models and textures.
please give me permission

**Comment by Kingdomall** [comment]
please do not use Wyrmroost Github for a long dead mod.
the textures are easy to get but the model is not. if you plan on using Fabric or MCreator, you will not have success.
many, many people have asked to port or maintain dm2, but we cannot do that for a number of reasons.
1. many of those people are irrisponsible
2. they want to use MCreator, which is a terrible mod creator
3. not many people have the capabilities to maintain a mod, especially one that has been thrown in the dumpster more than once
4. it's not worth the effort. if you want to make anything worth while, you would need to completely rewrite the code.

**Comment by MiahDragon** [comment]
so is it ok if i use the code and textures. its not going to count as stealing if i use dragon mounts 2 as a base for my mod?

**Comment by Kingdomall** [comment]
no, I wouldn't recommend you do that. the code is horrendous and unusable. also, you can't use the textures without the model.
