### ISSUE TITLE
RoostStalker disappearing from head 

### ISSUE THREAD

**Issue by d4rkdr4g0n11** [WolfShotz/Wyrmroost#87]
When I try to tame roost stalker with eggs, these purple/black particles show, and no hearts show at all no matter how much I feed them. Iam able to put them on my head tho, but they disappear into thin air in a couple seconds. (No crouching)

**Comment by WolfShotz** [comment]
Potentially a desync problem

**Comment by WolfShotz** [comment]
Could not Reproduce
