### ISSUE TITLE
The Dragon Fruit Drake's ability won't work at all

### ISSUE THREAD

**Issue by Shinonox** [WolfShotz/Wyrmroost#90]
Dragon Fruit Drake's are capable of clearing large amounts of grass, flowers etc. Yet, in the latest version for 1.15.2, I tried to use the ability (By pressing V while riding it), the animation played but nothing around me was destroyed. So I tried again and it still didn't work, so I'm positive this is a bug. Please look into it, thank you.

**Comment by WolfShotz** [comment]
confirmed bug yes

**Comment by WolfShotz** [comment]
Fixed in 1.1.3
