### ISSUE TITLE
canari wyvern eggs not hatching

### ISSUE THREAD

**Issue by Robomnz** [WolfShotz/Wyrmroost#91]
bred my canari wyverns at the same time as my silver gliders and my silver glider eggs all hatched after 10 minutes but my canari wyvern eggs are not hatching and they are supposed to hatch after 5 minutes, when i picked up the eggs again all said they still had 5 minutes remaining

the same thing seems to happen to butterfly leviathan eggs placed in creative mode
![image](https://user-images.githubusercontent.com/34904608/88757693-bd673000-d1ba-11ea-8661-2dd09ab8e605.png)
![image](https://user-images.githubusercontent.com/34904608/88757730-cf48d300-d1ba-11ea-965a-b768b2b7ed1a.png)

**Comment by WolfShotz** [comment]
Intentional Behavior:
Canari Eggs hatch on Jungle Leaves
Butterfly Leviathan eggs hatch in water
