### ISSUE TITLE
in the 1.15.2 version there are a few bugs i noticed:  1. Drake's siting positon  2. When you hide your dragon in soul Crystal, and when you want to place him, there is an error: item.wyrmroost.soul_crystal.fail_message  3. Blue geode armor has no textures when put on Drake. I'd like you to checks these bugs, thank you

### ISSUE THREAD

**Issue by TalkingPickle** [WolfShotz/Wyrmroost#94]
**Logs:** {Link(s) to GitHub Gist, Pastebin, etc with full latest.log and/or crash report}

**Steps to Reproduce:**
 1. Do this
 2. Then do that
 3. ...

**Description of issue:**

**Comment by WolfShotz** [comment]
Please keep the title relatively simple. Its like putting the subject line in an email.

These issues have already been reported, marking as duplicates
