### ISSUE TITLE
Soul Crystals keep deleting dragons inside them on server

### ISSUE THREAD

**Issue by dianamonde** [WolfShotz/Wyrmroost#95]
In the latest 1.15.2 version of wyrmroost, soul crystals, when on server, will delete dragons inside them for a variety of reasons

Reasons I found:
-Dying on keepInventory respawns you with the soul crystal glitched and not working
-Sometimes dropping them placing them on a chest seems to have this effect
-Sometimes they will do this due to being reused too fast
-Sometimes they simply will do this randomly with no other apparent reasons

this seems really inconsistent, but sometimes a server restart fixes the soul crystal and lets the dragon respawn, but ive only managed to successfully do this on the last 2 causes

**Comment by WolfShotz** [comment]
Fixed in 1.1.3
