### ISSUE TITLE
I'm trying to tame a Butterfly Leviathan, but it isn't working

### ISSUE THREAD

**Issue by Shinonox** [WolfShotz/Wyrmroost#99]
So, I was able to beach a Butterfly Leviathan, but it isn't attempting to strike me with lightning. I've tried multiple times to tame it, but it just sits in one spot, doesn't even try to chase me.

**Comment by WolfShotz** [comment]
Its very slow on land, and it needs to bet wet in order for it to strike lightning. (So in water, or if its raining)
